/* *** Help Application - Version 1.1.0 Back-out script *** */

SET FOREIGN_KEY_CHECKS = 0;

DROP VIEW IF EXISTS HELP_V_RESOURCE;

DROP TABLE IF EXISTS AF_BLLTN_MSG;
DROP TABLE IF EXISTS AF_USER;

DROP TABLE IF EXISTS HELP_R_RSC_TYPE;
DROP TABLE IF EXISTS HELP_R_RSC_SUBCAT;
DROP TABLE IF EXISTS HELP_R_RSC_CAT;
DROP TABLE IF EXISTS HELP_R_RSC_STS;
DROP TABLE IF EXISTS HELP_R_RSC_TAG;
DROP TABLE IF EXISTS HELP_RSC_CMMNT;
DROP TABLE IF EXISTS HELP_RSC_FILE;
DROP TABLE IF EXISTS HELP_RSC_LNK;
DROP TABLE IF EXISTS HELP_RSC_RATING;
DROP TABLE IF EXISTS HELP_L_RSC_TAG;
DROP TABLE IF EXISTS HELP_RSC;

SET FOREIGN_KEY_CHECKS = 1;