/* ***** AF Common Objects Release 2.0 SQL Script to create database ***** */  
 
/* ***** DROP VIEWS IF EXIST ***** */ 

/* ***** DROP TABLES IF EXIST ***** */

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS AF_R_DATA;
DROP TABLE IF EXISTS AF_BLLTN_MSG;
DROP TABLE IF EXISTS AF_USER;

SET FOREIGN_KEY_CHECKS = 1;

/* ***** CREATE REFERENCE TABLES ***** */

CREATE TABLE `AF_R_DATA` (
  `R_ID` int(10) NOT NULL  AUTO_INCREMENT,
  `R_TYPE` varchar(255) NOT NULL,
  `R_LABEL` varchar(255) NOT NULL,
  `R_IS_ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ***** CREATE TABLES ***** */

CREATE TABLE `AF_BLLTN_MSG` (
  `BLLTIN_M_ID` int(10) NOT NULL AUTO_INCREMENT,
  `BLLTIN_M_VAL` varchar(4000) NOT NULL,
  `BLLTIN_M_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BLLTIN_M_CRT_USR` varchar(50) NOT NULL,
  `BLLTIN_M_STRT_DT` datetime NOT NULL,
  `BLLTIN_M_END_DT` datetime NOT NULL,
  `BLLTIN_M_LST_MOD_DT` datetime DEFAULT NULL,
  `BLLTIN_M_LST_MOD_USR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`BLLTIN_M_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AF_USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPIAN_USERNAME` varchar(255) NOT NULL,
  `USER_FIRST_NAME` varchar(255) DEFAULT NULL,
  `USER_MIDDLE_NAME` varchar(255) DEFAULT NULL,
  `USER_LAST_NAME` varchar(255) DEFAULT NULL,
  `USER_EMAIL` varchar(255) DEFAULT NULL,
  `USER_OFFICE_PHONE` varchar(255) DEFAULT NULL,
  `USER_MOBILE_PHONE` varchar(255) DEFAULT NULL,
  `USER_HOME_PHONE` varchar(255) DEFAULT NULL,
  `USER_ADDR1` varchar(255) DEFAULT NULL,
  `USER_ADDR2` varchar(255) DEFAULT NULL,
  `USER_ADDR3` varchar(255) DEFAULT NULL,
  `USER_CITY` varchar(255) DEFAULT NULL,
  `USER_STATE` varchar(255) DEFAULT NULL,
  `USER_ZIP` varchar(255) DEFAULT NULL,
  `USER_COUNTRY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ***** UPDATE TABLES WITH CONSTRAINTS ***** */ 

/* ***** CREATE VIEWS ***** */