/*
  EFM_DROP_MYSQL.sql
  Drop script for Fleet Management Application
*/

/* Remove EFM Foreign Key Constraints */

ALTER TABLE EFM_EXPENSE DROP FOREIGN KEY IF EXISTS FK_EFM_EXPENSE_CATEGORY;
ALTER TABLE EFM_EXPENSE DROP FOREIGN KEY IF EXISTS FK_EFM_VEHICLE;
ALTER TABLE EFM_L_LOCATION_USER DROP FOREIGN KEY IF EXISTS FK_EFM_LOCATION;
ALTER TABLE EFM_L_LOCATION_USER DROP FOREIGN KEY IF EXISTS FK_EFM_USER;
ALTER TABLE EFM_L_VEHICLE_USER DROP FOREIGN KEY IF EXISTS FK_EFM_VEHICLE;
ALTER TABLE EFM_L_VEHICLE_USER DROP FOREIGN KEY IF EXISTS FK_EFM_USER;
ALTER TABLE EFM_MAINTENANCE_LOG DROP FOREIGN KEY IF EXISTS FK_EFM_VEHICLE;
ALTER TABLE EFM_VEHICLE DROP FOREIGN KEY IF EXISTS FK_EFM_VEH_STATUS;
ALTER TABLE EFM_VEHICLE DROP FOREIGN KEY IF EXISTS FK_EFM_VEH_TYPE;

/* Remove Home-To-Work Foreign Key Constraints */



/* Drop Tables */

DROP TABLE IF EXISTS EFM_EXPENSE;
DROP TABLE IF EXISTS EFM_FLEET;
DROP TABLE IF EXISTS EFM_LOCATION;
DROP TABLE IF EXISTS EFM_L_LOCATION_USER;
DROP TABLE IF EXISTS EFM_L_VEHICLE_USER;
DROP TABLE IF EXISTS EFM_MAINTENANCE_LOG;
DROP TABLE IF EXISTS EFM_R_VEH_EOL_REASON;
DROP TABLE IF EXISTS EFM_R_EXP_CATEGORY;
DROP TABLE IF EXISTS EFM_R_VEH_STATUS;
DROP TABLE IF EXISTS EFM_R_VEC_TYPE;
DROP TABLE IF EXISTS EFM_TRIP;
DROP TABLE IF EXISTS EFM_USER;
DROP TABLE IF EXISTS EFM_VEHICLE;
DROP TABLE IF EXISTS EFM_VEHICLE_USAGE;



/* Drop Views */


/* Drop Procedures */


/* Drop Home-To-Work Specific Objects */
DROP TABLE IF EXISTS EFM_HTW_EXPENSES;
