/* ***** CTS Release 1.0.0 SQL Script to create database ***** */  
 
/* ***** DROP VIEWS IF EXIST ***** */ 

/* ***** DROP TABLES IF EXIST ***** */

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CTS_R_DOC_TYPE;
DROP TABLE IF EXISTS CTS_R_DOC_AUDIT_ACTION;
DROP TABLE IF EXISTS CTS_R_FLDR_STAGE;
DROP TABLE IF EXISTS CTS_R_FLDR_CTGRY;
DROP TABLE IF EXISTS CTS_R_FLDR_TYPE;
DROP TABLE IF EXISTS CTS_R_FLDR_SUBTYPE;
DROP TABLE IF EXISTS CTS_R_FLDR_SEC_TYPE;
DROP TABLE IF EXISTS CTS_R_FLDR_FILE_SERIES;
DROP TABLE IF EXISTS CTS_R_ORIG_TITLE;
DROP TABLE IF EXISTS CTS_R_INT_ORIG_OFFICE;
DROP TABLE IF EXISTS CTS_R_REF_OFFICE;
DROP TABLE IF EXISTS CTS_R_START_OFFICE;
DROP TABLE IF EXISTS CTS_R_SIGN_OFFICE;
DROP TABLE IF EXISTS CTS_R_SIGN_TYPE;
DROP TABLE IF EXISTS CTS_R_FLDR_CLOSE_RSN;
DROP TABLE IF EXISTS CTS_R_FLDR_DUE_DATE;
DROP TABLE IF EXISTS CTS_R_FLDR_AUDIT_ACTION;
DROP TABLE IF EXISTS CTS_R_ASSGN_PRIORITY;
DROP TABLE IF EXISTS CTS_R_ASSGN_STATUS;
DROP TABLE IF EXISTS CTS_R_ASSGN_AUDIT_ACTION;
DROP TABLE IF EXISTS CTS_R_TASK_TYPE;

DROP TABLE IF EXISTS CTS_DOC;
DROP TABLE IF EXISTS CTS_DOC_TAG;
DROP TABLE IF EXISTS CTS_L_DOC_TAG;
DROP TABLE IF EXISTS CTS_FLDR;
DROP TABLE IF EXISTS CTS_L_FLDR_DOC;
DROP TABLE IF EXISTS CTS_FLDR_NOTES;
DROP TABLE IF EXISTS CTS_ASSGN;
DROP TABLE IF EXISTS CTS_SV_WRKFLW;
DROP TABLE IF EXISTS CTS_SV_WRKFLW_ASSGN;

DROP TABLE IF EXISTS CTS_DOC_AUDIT;
DROP TABLE IF EXISTS CTS_FLDR_AUDIT;
DROP TABLE IF EXISTS CTS_ASSGN_AUDIT;
DROP TABLE IF EXISTS CTS_TASK_METRICS;
 
SET FOREIGN_KEY_CHECKS = 1;


/* ***** CREATE REFERENCE TABLES ***** */

CREATE TABLE `CTS_R_DOC_TYPE` (
  `R_DOC_T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_DOC_T_VAL` varchar(100) NOT NULL,
  `R_DOC_T_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_DOC_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_DOC_AUDIT_ACTION` (
  `R_DOC_AUDIT_A_ID` int(10) NOT NULL,
  `R_DOC_AUDIT_A_VAL` varchar(100) NOT NULL,
  `R_DOC_AUDIT_A_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_DOC_AUDIT_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `CTS_R_FLDR_STAGE` (
  `R_FLDR_S_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_S_VAL` varchar(100) NOT NULL,
  `R_FLDR_S_ORDER` int(10) NOT NULL,
  `R_FLDR_S_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_S_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_CTGRY` (
  `R_FLDR_CR_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_CR_VAL` varchar(100) NOT NULL,
  `R_FLDR_CR_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_CR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_TYPE` (
  `R_FLDR_T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_CR_ID` int(10) NOT NULL,
  `R_FLDR_T_VAL` varchar(100) NOT NULL,
  `R_FLDR_T_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_SUBTYPE` (
  `R_FLDR_S_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_T_ID` int(10) NOT NULL,
  `R_FLDR_S_VAL` varchar(100) NOT NULL,
  `R_FLDR_S_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_S_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_SEC_TYPE` (
  `R_FLDR_ST_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_ST_VAL` varchar(100) NOT NULL,
  `R_FLDR_ST_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_FILE_SERIES` (
  `R_FLDR_FS_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_FS_VAL` varchar(100) NOT NULL,
  `R_FLDR_FS_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_FS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_ORIG_TITLE` (
  `R_ORIG_T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_ORIG_T_VAL` varchar(100) NOT NULL,
  `R_ORIG_T_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_ORIG_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_INT_ORIG_OFFICE` (
  `R_IOO_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_IOO_VAL` varchar(100) NOT NULL,
  `R_IOO_CODE` varchar(50) NOT NULL,
  `R_IOO_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_IOO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_REF_OFFICE` (
  `R_REF_O_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_REF_O_VAL` varchar(100) NOT NULL,
  `R_REF_O_CODE` varchar(50) NOT NULL,
  `R_REF_O_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_REF_O_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_START_OFFICE` (
  `R_START_O_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_START_O_VAL` varchar(100) NOT NULL,
  `R_START_O_CODE` varchar(50) NOT NULL,
  `R_START_O_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_START_O_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `CTS_R_SIGN_OFFICE` (
  `R_SIGN_O_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_SIGN_O_VAL` varchar(100) DEFAULT NULL,
  `R_SIGN_O_CODE` varchar(50) NOT NULL,
  `R_SIGN_O_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_SIGN_O_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_SIGN_TYPE` (
  `R_SIGN_T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_SIGN_T_VAL` varchar(100) NOT NULL,
  `R_SIGN_T_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_SIGN_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_CLOSE_RSN` (
  `R_FLDR_CR_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_CR_VAL` varchar(100) NOT NULL,
  `R_FLDR_CR_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_CR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_DUE_DATE` (
  `R_FLDR_DD_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_FLDR_T_ID` int(10) NOT NULL,
  `R_FLDR_DD_VAL` int(10) NOT NULL,
  `R_FLDR_DD_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_DD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_FLDR_AUDIT_ACTION` (
  `R_FLDR_AUDIT_A_ID` int(10) NOT NULL,
  `R_FLDR_AUDIT_A_VAL` varchar(100) NOT NULL,
  `R_FLDR_AUDIT_A_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_FLDR_AUDIT_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `CTS_R_ASSGN_PRIORITY` (
  `R_ASSGN_P_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_ASSGN_P_VAL` varchar(100) NOT NULL,
  `R_ASSGN_P_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_ASSGN_P_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_ASSGN_STATUS` (
  `R_ASSGN_S_ID` int(10) NOT NULL AUTO_INCREMENT,
  `R_ASSGN_S_VAL` varchar(100) NOT NULL,
  `R_ASSGN_S_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  `R_ASSGN_S_ORDER` int(10) NOT NULL,
  PRIMARY KEY (`R_ASSGN_S_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_ASSGN_AUDIT_ACTION` (
  `R_ASSGN_AUDIT_A_ID` int(10) NOT NULL,
  `R_ASSGN_AUDIT_A_VAL` varchar(100) NOT NULL,
  `R_ASSGN_AUDIT_A_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_ASSGN_AUDIT_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_R_TASK_TYPE` (
  `R_TASK_T_ID` int(10) NOT NULL  AUTO_INCREMENT,
  `R_TASK_T_VAL` varchar(100) NOT NULL,
  `R_TASK_T_ACTV_FLG` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`R_TASK_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* ***** CREATE TABLES ***** */

CREATE TABLE `CTS_DOC` (
  `DOC_ID` int(10) NOT NULL AUTO_INCREMENT,
  `DOC_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DOC_CRT_USR` varchar(50) NOT NULL,
  `DOC_DT` datetime DEFAULT NULL,
  `DOC_SUBJECT` varchar(255) DEFAULT NULL,
  `R_DOC_T_ID` int(10) NOT NULL,
  `DOC_LST_MOD_DT` datetime DEFAULT NULL,
  `DOC_LST_MOD_USR` varchar(50) DEFAULT NULL,
  `DOC_AUTHOR` varchar(100) DEFAULT NULL,
  `DOC_COMMENTS` varchar(4000) DEFAULT NULL,
  `DOC_CHECKED_OUT_TO` varchar(255) DEFAULT NULL,
  `DOC_TITLE` varchar(255) DEFAULT NULL,
  `DOC_APN_DOC_ID` int(10) NOT NULL,
  `DOC_TMPLT_FLAG` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`DOC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_DOC_TAG` (
  `DOC_T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `DOC_T_VAL` varchar(50) NOT NULL,
  PRIMARY KEY (`DOC_T_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_L_DOC_TAG` (
  `DOC_ID` int(10) NOT NULL,
  `DOC_T_ID` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_FLDR` (
  `FLDR_ID` int(10) NOT NULL AUTO_INCREMENT,
  `FLDR_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FLDR_CRT_USR` varchar(50) NOT NULL,
  `FLDR_EXT_ID` varchar(100) DEFAULT NULL,
  `FLDR_EXT_SYS_NAME` varchar(255) DEFAULT NULL,
  `FLDR_DUE_DT` datetime DEFAULT NULL,
  `FLDR_EXT_INQUIRY_NMBR` varchar(50) DEFAULT NULL,
  `FLDR_ADDRESSEE` varchar(255) DEFAULT NULL,
  `R_FLDR_CTGRY_ID` int(10) DEFAULT NULL,
  `R_FLDR_FS_ID` int(10) DEFAULT NULL,
  `FLDR_INSTRUCTIONS` varchar(4000) DEFAULT NULL,
  `FLDR_CLOSE_DT` datetime DEFAULT NULL,
  `R_FLDR_CLOSE_RSN_ID` int(10) DEFAULT NULL,
  `R_IOO_ID` int(10) DEFAULT NULL,
  `FLDR_ORIGINATOR` varchar(255) DEFAULT NULL,
  `R_ORIG_T_ID` int(10) DEFAULT NULL,
  `FLDR_RECEIVED_DT` datetime DEFAULT NULL,
  `R_REF_O_ID` int(10) DEFAULT NULL,
  `FLDR_RETENTION_DT` datetime DEFAULT NULL,
  `FLDR_SIGN_USR` varchar(50) DEFAULT NULL,
  `FLDR_SIGN_DT` datetime DEFAULT NULL,
  `R_SIGN_O_ID` int(10) DEFAULT NULL,
  `R_SIGN_T_ID` int(10) DEFAULT NULL,
  `R_START_O_ID` int(10) DEFAULT NULL,
  `R_FLDR_STAGE_ID` int(10) DEFAULT NULL,
  `FLDR_OPEN_FLAG` tinyint(1) DEFAULT NULL,
  `FLDR_SUBJECT` varchar(255) DEFAULT NULL,
  `R_FLDR_TYPE_ID` int(10) DEFAULT NULL,
  `R_FLDR_SUBTYPE_ID` int(10) DEFAULT NULL,
  `FLDR_LST_MOD_DT` datetime DEFAULT NULL,
  `FLDR_LST_MOD_USR` varchar(50) DEFAULT NULL,
  `FLDR_OWNER` varchar(50) DEFAULT NULL,
  `R_FLDR_ST_ID` int(10) DEFAULT NULL,
  `FLDR_DESCRIPTION` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`FLDR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_L_FLDR_DOC` (
  `LINK_ID` int(10) NOT NULL AUTO_INCREMENT,
  `DOC_ID` int(10) DEFAULT NULL,
  `FLDR_ID` int(10) NOT NULL,
  `LINK_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LINK_CRT_USR` varchar(50) NOT NULL,
  PRIMARY KEY (`LINK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_FLDR_NOTES` (
  `FLDR_N_ID` int(10) NOT NULL AUTO_INCREMENT,
  `FLDR_N_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FLDR_N_CRT_USR` varchar(50) NOT NULL,
  `FLDR_N_LST_MOD_USR` varchar(50) DEFAULT NULL,
  `FLDR_N_LST_MOD_DT` datetime DEFAULT NULL,
  `FLDR_N_NOTE` varchar(4000) NOT NULL,
  `FLDR_ID` int(10) NOT NULL,
  `FLDR_N_DEL_USR` varchar(50) DEFAULT NULL,
  `FLDR_N_DEL_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`FLDR_N_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_ASSGN` (
  `ASSGN_ID` int(10) NOT NULL AUTO_INCREMENT,
  `ASSGN_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ASSGN_CRT_USR` varchar(50) NOT NULL,
  `ASSGN_ASSGNMNT` varchar(255) NOT NULL,
  `ASSGN_DUE_DT` datetime NOT NULL,
  `ASSGN_STRT_DT` datetime DEFAULT NULL,
  `ASSGN_CMPLTD_USR` varchar(50) DEFAULT NULL,
  `ASSGN_CMPLTD_DT` datetime DEFAULT NULL,
  `ASSGN_SUBJECT` varchar(255) NOT NULL,
  `ASSGN_INSTRUCTIONS` varchar(4000) DEFAULT NULL,
  `ASSGN_SEQENCE` int(10) DEFAULT NULL,
  `R_ASSGN_S_ID` int(10) DEFAULT NULL,
  `ASSGN_LST_MOD_DT` datetime DEFAULT NULL,
  `ASSGN_LST_MOD_USR` varchar(50) DEFAULT NULL,
  `FLDR_ID` int(10) NOT NULL,
  `R_ASSGN_P_ID` int(10) DEFAULT NULL,
  `ASSGN_DEL_USR` varchar(50) DEFAULT NULL,
  `ASSGN_DEL_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`ASSGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_SV_WRKFLW` (
  `WRKFLW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `WRKFLW_NAME` varchar(255) NOT NULL,
  `WRKFLW_DESC` varchar(4000) NOT NULL,
  `WRKFLW_SYSTEM_FLG` tinyint(1) NOT NULL,
  `WRKFLW_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `WRKFLW_CRT_USR` varchar(50) NOT NULL,
  `WRKFLW_LST_MOD_DT` datetime DEFAULT NULL,
  `WRKFLW_LST_MOD_USR` varchar(50) DEFAULT NULL,
  `WRKFLW_DEL_USR` varchar(50) DEFAULT NULL,
  `WRKFLW_DEL_DT` datetime DEFAULT NULL,
  PRIMARY KEY (`WRKFLW_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_SV_WRKFLW_ASSGN` (
  `ASSGN_ID` int(10) NOT NULL AUTO_INCREMENT,
  `WRKFLW_ID` int(11) NOT NULL,
  `ASSGN_CRT_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ASSGN_CRT_USR` varchar(50) NOT NULL,
  `ASSGN_ASSGNMNT` varchar(255) NOT NULL,
  `ASSGN_DUE_DT` datetime DEFAULT NULL,
  `ASSGN_SUBJECT` varchar(255) NOT NULL,
  `ASSGN_INSTRUCTIONS` varchar(4000) DEFAULT NULL,
  `ASSGN_SEQENCE` int(10) DEFAULT NULL,
  `R_ASSGN_S_ID` int(10) DEFAULT NULL,
  `R_ASSGN_P_ID` int(10) DEFAULT NULL,
  `ASSGN_LST_MOD_DT` datetime DEFAULT NULL,
  `ASSGN_LST_MOD_USR` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ASSGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `CTS_DOC_AUDIT` (
  `DOC_A_ID` int(10) NOT NULL AUTO_INCREMENT,
  `DOC_ID` int(10) NOT NULL,
  `R_DOC_AUDIT_A_ID` int(10) NOT NULL,
  `DOC_A_USER` varchar(50) DEFAULT NULL,
  `DOC_A_DT` datetime DEFAULT NULL,
  `DOC_A_OLD_VAL` varchar(255) DEFAULT NULL,
  `DOC_A_NEW_VAL` varchar(255) DEFAULT NULL,
  `TASK_M_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`DOC_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_FLDR_AUDIT` (
  `FLDR_A_ID` int(10) NOT NULL AUTO_INCREMENT,
  `FLDR_ID` int(10) NOT NULL,
  `R_FLDR_AUDIT_A_ID` int(10) NOT NULL,
  `FLDR_A_USER` varchar(50) DEFAULT NULL,
  `FLDR_A_DT` datetime DEFAULT NULL,
  `FLDR_A_OLD_VAL` varchar(255) DEFAULT NULL,
  `FLDR_A_NEW_VAL` varchar(255) DEFAULT NULL,
  `TASK_M_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`FLDR_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_ASSGN_AUDIT` (
  `ASSGN_A_ID` int(10) NOT NULL AUTO_INCREMENT,
  `ASSGN_ID` int(10) NOT NULL,
  `R_ASSGN_AUDIT_A_ID` int(10) NOT NULL,
  `ASSGN_A_USER` varchar(50) DEFAULT NULL,
  `ASSGN_A_DT` datetime DEFAULT NULL,
  `ASSGN_A_OLD_VAL` varchar(255) DEFAULT NULL,
  `ASSGN_A_NEW_VAL` varchar(255) DEFAULT NULL,
  `TASK_M_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`ASSGN_A_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CTS_TASK_METRICS` (
  `TASK_M_ID` int(10) NOT NULL AUTO_INCREMENT,
  `TASK_M_APN_TASK_ID` varchar(50) NOT NULL,
  `TASK_M_STRT_DT` datetime DEFAULT NULL,
  `TASK_M_ASSGNMT` varchar(250) DEFAULT NULL,
  `TASK_M_OWNER` varchar(50) DEFAULT NULL,
  `TASK_M_END_DT` datetime DEFAULT NULL,
  `TASK_M_DEADLINE` datetime DEFAULT NULL,
  `R_TASK_T_ID` int(10) NOT NULL,
  `DOC_ID` int(10) DEFAULT NULL,
  `FLDR_ID` int(10) DEFAULT NULL,
  PRIMARY KEY (`TASK_M_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* ***** UPDATE TABLES WITH CONSTRAINTS ***** */ 

ALTER TABLE `CTS_R_FLDR_STAGE`
  ADD UNIQUE KEY `R_FLDR_S_ORDER` (`R_FLDR_S_ORDER`);
  
ALTER TABLE `CTS_R_FLDR_TYPE`
  ADD CONSTRAINT `CTS_R_FLDR_TYPE_ibfk_1` FOREIGN KEY (`R_FLDR_CR_ID`) REFERENCES `CTS_R_FLDR_CTGRY` (`R_FLDR_CR_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_R_FLDR_SUBTYPE`
  ADD CONSTRAINT `CTS_R_FLDR_SUBTYPE_ibfk_1` FOREIGN KEY (`R_FLDR_T_ID`) REFERENCES `CTS_R_FLDR_TYPE` (`R_FLDR_T_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_R_FLDR_DUE_DATE`
  ADD CONSTRAINT `CTS_R_FLDR_DUE_DATE_ibfk_1` FOREIGN KEY (`R_FLDR_T_ID`) REFERENCES `CTS_R_FLDR_TYPE` (`R_FLDR_T_ID`) ON DELETE CASCADE;

ALTER TABLE `CTS_R_ASSGN_STATUS`
  ADD UNIQUE KEY `R_ASSGN_S_ORDER` (`R_ASSGN_S_ORDER`);

ALTER TABLE `CTS_DOC`
  ADD UNIQUE KEY `DOC_APN_DOC_ID` (`DOC_APN_DOC_ID`);
  
ALTER TABLE `CTS_DOC`
  ADD CONSTRAINT `CTS_DOC_ibfk_1` FOREIGN KEY (`R_DOC_T_ID`) REFERENCES `CTS_R_DOC_TYPE` (`R_DOC_T_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_L_DOC_TAG`
  ADD CONSTRAINT `CTS_L_DOC_TAG_ibfk_1` FOREIGN KEY (`DOC_ID`) REFERENCES `CTS_DOC` (`DOC_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_L_DOC_TAG_ibfk_2` FOREIGN KEY (`DOC_T_ID`) REFERENCES `CTS_DOC_TAG` (`DOC_T_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_FLDR`
  ADD CONSTRAINT `CTS_FLDR_ibfk_1` FOREIGN KEY (`R_FLDR_FS_ID`) REFERENCES `CTS_R_FLDR_FILE_SERIES` (`R_FLDR_FS_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_10` FOREIGN KEY (`R_FLDR_STAGE_ID`) REFERENCES `CTS_R_FLDR_STAGE` (`R_FLDR_S_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_11` FOREIGN KEY (`R_FLDR_CLOSE_RSN_ID`) REFERENCES `CTS_R_FLDR_CLOSE_RSN` (`R_FLDR_CR_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_12` FOREIGN KEY (`R_SIGN_O_ID`) REFERENCES `CTS_R_SIGN_OFFICE` (`R_SIGN_O_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_13` FOREIGN KEY (`R_SIGN_T_ID`) REFERENCES `CTS_R_SIGN_TYPE` (`R_SIGN_T_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_2` FOREIGN KEY (`R_FLDR_TYPE_ID`) REFERENCES `CTS_R_FLDR_TYPE` (`R_FLDR_T_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_3` FOREIGN KEY (`R_FLDR_SUBTYPE_ID`) REFERENCES `CTS_R_FLDR_SUBTYPE` (`R_FLDR_S_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_4` FOREIGN KEY (`R_FLDR_ST_ID`) REFERENCES `CTS_R_FLDR_SEC_TYPE` (`R_FLDR_ST_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_5` FOREIGN KEY (`R_IOO_ID`) REFERENCES `CTS_R_INT_ORIG_OFFICE` (`R_IOO_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_6` FOREIGN KEY (`R_REF_O_ID`) REFERENCES `CTS_R_REF_OFFICE` (`R_REF_O_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_7` FOREIGN KEY (`R_START_O_ID`) REFERENCES `CTS_R_START_OFFICE` (`R_START_O_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_8` FOREIGN KEY (`R_FLDR_CTGRY_ID`) REFERENCES `CTS_R_FLDR_CTGRY` (`R_FLDR_CR_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_ibfk_9` FOREIGN KEY (`R_ORIG_T_ID`) REFERENCES `CTS_R_ORIG_TITLE` (`R_ORIG_T_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_L_FLDR_DOC`
  ADD CONSTRAINT `CTS_L_FLDR_DOC_ibfk_1` FOREIGN KEY (`DOC_ID`) REFERENCES `CTS_DOC` (`DOC_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_L_FLDR_DOC_ibfk_2` FOREIGN KEY (`FLDR_ID`) REFERENCES `CTS_FLDR` (`FLDR_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_FLDR_NOTES`
  ADD CONSTRAINT `CTS_FLDR_NOTES_ibfk_1` FOREIGN KEY (`FLDR_ID`) REFERENCES `CTS_FLDR` (`FLDR_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_ASSGN`
  ADD CONSTRAINT `CTS_ASSGN_ibfk_2` FOREIGN KEY (`R_ASSGN_S_ID`) REFERENCES `CTS_R_ASSGN_STATUS` (`R_ASSGN_S_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_ASSGN_ibfk_3` FOREIGN KEY (`FLDR_ID`) REFERENCES `CTS_FLDR` (`FLDR_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_ASSGN_ibfk_4` FOREIGN KEY (`R_ASSGN_P_ID`) REFERENCES `CTS_R_ASSGN_PRIORITY` (`R_ASSGN_P_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_SV_WRKFLW_ASSGN`
  ADD CONSTRAINT `CTS_SV_WRKFLW_ASSGN_ibfk_1` FOREIGN KEY (`WRKFLW_ID`) REFERENCES `CTS_SV_WRKFLW` (`WRKFLW_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `CTS_SV_WRKFLW_ASSGN_ibfk_2` FOREIGN KEY (`R_ASSGN_S_ID`) REFERENCES `CTS_R_ASSGN_STATUS` (`R_ASSGN_S_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `CTS_SV_WRKFLW_ASSGN_ibfk_3` FOREIGN KEY (`R_ASSGN_P_ID`) REFERENCES `CTS_R_ASSGN_PRIORITY` (`R_ASSGN_P_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
  
ALTER TABLE `CTS_DOC_AUDIT`
  ADD CONSTRAINT `CTS_DOC_AUDIT_ibfk_1` FOREIGN KEY (`DOC_ID`) REFERENCES `CTS_DOC` (`DOC_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_DOC_AUDIT_ibfk_2` FOREIGN KEY (`R_DOC_AUDIT_A_ID`) REFERENCES `CTS_R_DOC_AUDIT_ACTION` (`R_DOC_AUDIT_A_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_DOC_AUDIT_ibfk_3` FOREIGN KEY (`TASK_M_ID`) REFERENCES `CTS_TASK_METRICS` (`TASK_M_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_FLDR_AUDIT`
  ADD CONSTRAINT `CTS_FLDR_AUDIT_ibfk_1` FOREIGN KEY (`FLDR_ID`) REFERENCES `CTS_FLDR` (`FLDR_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_AUDIT_ibfk_2` FOREIGN KEY (`R_FLDR_AUDIT_A_ID`) REFERENCES `CTS_R_FLDR_AUDIT_ACTION` (`R_FLDR_AUDIT_A_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_FLDR_AUDIT_ibfk_3` FOREIGN KEY (`TASK_M_ID`) REFERENCES `CTS_TASK_METRICS` (`TASK_M_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_ASSGN_AUDIT`
  ADD CONSTRAINT `CTS_ASSGN_AUDIT_ibfk_1` FOREIGN KEY (`ASSGN_ID`) REFERENCES `CTS_ASSGN` (`ASSGN_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_ASSGN_AUDIT_ibfk_2` FOREIGN KEY (`R_ASSGN_AUDIT_A_ID`) REFERENCES `CTS_R_ASSGN_AUDIT_ACTION` (`R_ASSGN_AUDIT_A_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_ASSGN_AUDIT_ibfk_3` FOREIGN KEY (`TASK_M_ID`) REFERENCES `CTS_TASK_METRICS` (`TASK_M_ID`) ON DELETE CASCADE;
  
ALTER TABLE `CTS_TASK_METRICS`
  ADD CONSTRAINT `CTS_TASK_METRICS_ibfk_1` FOREIGN KEY (`R_TASK_T_ID`) REFERENCES `CTS_R_TASK_TYPE` (`R_TASK_T_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_TASK_METRICS_ibfk_2` FOREIGN KEY (`DOC_ID`) REFERENCES `CTS_DOC` (`DOC_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `CTS_TASK_METRICS_ibfk_3` FOREIGN KEY (`FLDR_ID`) REFERENCES `CTS_FLDR` (`FLDR_ID`) ON DELETE CASCADE;


/* ***** CREATE VIEWS ***** */

CREATE OR REPLACE VIEW `CTS_V_DOC`  AS  
select 
  `doc`.`DOC_ID` AS `DOC_ID`,
  `doc`.`DOC_CRT_DT` AS `DOC_CRT_DT`,
  `doc`.`DOC_CRT_USR` AS `DOC_CRT_USR`,
  `doc`.`DOC_DT` AS `DOC_DT`,
  `doc`.`DOC_SUBJECT` AS `DOC_SUBJECT`,
  `doc`.`R_DOC_T_ID` AS `R_DOC_T_ID`,
  `typ`.`R_DOC_T_VAL` AS `R_DOC_T_VAL`,
  `doc`.`DOC_LST_MOD_DT` AS `DOC_LST_MOD_DT`,
  `doc`.`DOC_LST_MOD_USR` AS `DOC_LST_MOD_USR`,
  `doc`.`DOC_AUTHOR` AS `DOC_AUTHOR`,
  `doc`.`DOC_COMMENTS` AS `DOC_COMMENTS`,
  `doc`.`DOC_CHECKED_OUT_TO` AS `DOC_CHECKED_OUT_TO`,
  `doc`.`DOC_TITLE` AS `DOC_TITLE`,
  `doc`.`DOC_APN_DOC_ID` AS `DOC_APN_DOC_ID`,
  `doc`.`DOC_TMPLT_FLAG` AS `DOC_TMPLT_FLAG` 
 from (`CTS_DOC` `doc` join `CTS_R_DOC_TYPE` `typ` on((`doc`.`R_DOC_T_ID` = `typ`.`R_DOC_T_ID`))) ;
 
 CREATE OR REPLACE VIEW `CTS_V_FLDR_LIST_VIEW`  AS  
select 
  `f`.`FLDR_ID` AS `FLDR_ID`,
  `f`.`FLDR_CRT_DT` AS `FLDR_CRT_DT`,
  `f`.`FLDR_CRT_USR` AS `FLDR_CRT_USR`,
  `f`.`FLDR_DUE_DT` AS `FLDR_DUE_DT`,
  `cat`.`R_FLDR_CR_ID` AS `R_FLDR_CR_ID`,
  `cat`.`R_FLDR_CR_VAL` AS `R_FLDR_CR_VAL`,
  `f`.`FLDR_CLOSE_DT` AS `FLDR_CLOSE_DT`,
  `stage`.`R_FLDR_S_VAL` AS `R_FLDR_S_VAL`,
  `stage`.`R_FLDR_S_ID` AS `R_FLDR_S_ID`,
  `f`.`FLDR_OPEN_FLAG` AS `FLDR_OPEN_FLAG`,
  `f`.`FLDR_SUBJECT` AS `FLDR_SUBJECT`,
  `ftype`.`R_FLDR_T_ID` AS `R_FLDR_T_ID`,
  `ftype`.`R_FLDR_T_VAL` AS `R_FLDR_T_VAL`,
  `f`.`FLDR_OWNER` AS `FLDR_OWNER`,
  `f`.`FLDR_DESCRIPTION` AS `FLDR_DESCRIPTION`,
  `f`.`R_START_O_ID` AS `R_START_O_ID`,
  `startoffice`.`R_START_O_CODE` AS `R_START_O_CODE` 
 from ((((`CTS_FLDR` `f` join `CTS_R_FLDR_CTGRY` `cat` on((`f`.`R_FLDR_CTGRY_ID` = `cat`.`R_FLDR_CR_ID`))) 
   join `CTS_R_FLDR_STAGE` `stage` on((`f`.`R_FLDR_STAGE_ID` = `stage`.`R_FLDR_S_ID`))) 
   join `CTS_R_FLDR_TYPE` `ftype` on((`f`.`R_FLDR_TYPE_ID` = `ftype`.`R_FLDR_T_ID`))) 
   join `CTS_R_START_OFFICE` `startoffice` on((`f`.`R_START_O_ID` = `startoffice`.`R_START_O_ID`))) ;
   
 CREATE OR REPLACE VIEW `CTS_V_LINK_DOC_FLDR`  AS  
select 
  `link`.`LINK_ID` AS `LINK_ID`,
  `link`.`DOC_ID` AS `DOC_ID`,
  `link`.`FLDR_ID` AS `FLDR_ID`,
  `link`.`LINK_CRT_DT` AS `LINK_CRT_DT`,
  `link`.`LINK_CRT_USR` AS `LINK_CRT_USR`,
  `fol`.`R_FLDR_CTGRY_ID` AS `R_FLDR_CTGRY_ID`,
  `cat`.`R_FLDR_CR_VAL` AS `R_FLDR_CR_VAL`,
  `fol`.`R_FLDR_TYPE_ID` AS `R_FLDR_TYPE_ID`,
  `ftype`.`R_FLDR_T_VAL` AS `R_FLDR_T_VAL`,
  `fol`.`FLDR_OPEN_FLAG` AS `FLDR_OPEN_FLAG`,
  `fol`.`FLDR_SUBJECT` AS `FLDR_SUBJECT`,
  `fol`.`FLDR_OWNER` AS `FLDR_OWNER`,
  `fol`.`FLDR_LST_MOD_DT` AS `FLDR_LST_MOD_DT`,
  `fol`.`FLDR_LST_MOD_USR` AS `FLDR_LST_MOD_USR`
 from ((`CTS_L_FLDR_DOC` `link` join `CTS_FLDR` `fol` on((`link`.`FLDR_ID` = `fol`.`FLDR_ID`))) 
   join `CTS_R_FLDR_CTGRY` `cat` on((`fol`.`R_FLDR_CTGRY_ID` = `cat`.`R_FLDR_CR_ID`))
   join `CTS_R_FLDR_TYPE` `ftype` on((`fol`.`R_FLDR_TYPE_ID` = `ftype`.`R_FLDR_T_ID`))) ;

 CREATE OR REPLACE VIEW `CTS_V_LINK_FLDR_DOC`  AS  
select 
  `link`.`LINK_ID` AS `LINK_ID`,
  `link`.`DOC_ID` AS `DOC_ID`,
  `link`.`FLDR_ID` AS `FLDR_ID`,
  `link`.`LINK_CRT_DT` AS `LINK_CRT_DT`,
  `link`.`LINK_CRT_USR` AS `LINK_CRT_USR`,
  `doc`.`DOC_DT` AS `DOC_DT`,
  `doc`.`DOC_SUBJECT` AS `DOC_SUBJECT`,
  `doc`.`R_DOC_T_ID` AS `R_DOC_T_ID`,
  `typ`.`R_DOC_T_VAL` AS `R_DOC_T_VAL`,
  `doc`.`DOC_AUTHOR` AS `DOC_AUTHOR`,
  `doc`.`DOC_CHECKED_OUT_TO` AS `DOC_CHECKED_OUT_TO`,
  `doc`.`DOC_TITLE` AS `DOC_TITLE`,
  `doc`.`DOC_APN_DOC_ID` AS `DOC_APN_DOC_ID`,
  `doc`.`DOC_TMPLT_FLAG` AS `DOC_TMPLT_FLAG`,
  `doc`.`DOC_LST_MOD_DT` AS `DOC_LST_MOD_DT`,
  `doc`.`DOC_LST_MOD_USR` AS `DOC_LST_MOD_USR`
 from ((`CTS_L_FLDR_DOC` `link` join `CTS_DOC` `doc` on((`link`.`DOC_ID` = `doc`.`DOC_ID`))) 
   join `CTS_R_DOC_TYPE` `typ` on((`doc`.`R_DOC_T_ID` = `typ`.`R_DOC_T_ID`))) ;
 
 CREATE OR REPLACE VIEW `CTS_V_FLDR_ASSGN`  AS  
select 
  `f`.`FLDR_ID` AS `FLDR_ID`,
  `f`.`FLDR_DUE_DT` AS `FLDR_DUE_DT`,
  `f`.`FLDR_CLOSE_DT` AS `FLDR_CLOSE_DT`,
  `f`.`FLDR_OPEN_FLAG` AS `FLDR_OPEN_FLAG`,
  `f`.`FLDR_SUBJECT` AS `FLDR_SUBJECT`,
  `ftype`.`R_FLDR_T_ID` AS `R_FLDR_T_ID`,
  `ftype`.`R_FLDR_T_VAL` AS `R_FLDR_T_VAL`,
  `f`.`FLDR_OWNER` AS `FLDR_OWNER`,
  `a`.`ASSGN_ASSGNMNT` AS `ASSGN_ASSGNMNT`,
  `a`.`ASSGN_INSTRUCTIONS` AS `ASSGN_INSTRUCTIONS`,
  `a`.`ASSGN_DUE_DT` AS `ASSGN_DUE_DT` 
 from ((`CTS_FLDR` `f` left join `CTS_R_FLDR_TYPE` `ftype` on((`f`.`R_FLDR_TYPE_ID` = `ftype`.`R_FLDR_T_ID`))) 
   left join `CTS_ASSGN` `a` on((`f`.`FLDR_ID` = `a`.`FLDR_ID`))) ;

CREATE OR REPLACE VIEW CTS_V_AUDIT AS
SELECT
  concat(`taskMetric`.`TASK_M_ID`,'-',docAudit.DOC_A_ID) AS `ID`,
  `taskMetric`.`TASK_M_ID` AS `TASK_M_ID`,
  `taskMetric`.`R_TASK_T_ID` AS `R_TASK_T_ID`,
  `taskMetric`.`DOC_ID` AS `DOC_ID`,
  `taskMetric`.`FLDR_ID` AS `FLDR_ID`,
  docAudit.DOC_A_ID AS `A_ID`,
  NULL AS `ASSGN_ID`,
  docAudit.DOC_A_USER AS `A_USER`,
  docAudit.DOC_A_DT AS `A_DT`,
  docAudit.R_DOC_AUDIT_A_ID AS `R_AUDIT_A_ID`,
  docAudit.DOC_A_OLD_VAL AS `A_OLD_VAL`,
  docAudit.DOC_A_NEW_VAL AS `A_NEW_VAL`
FROM
  (`CTS_TASK_METRICS` `taskMetric` JOIN `CTS_DOC_AUDIT` `docAudit` ON ((`docAudit`.`TASK_M_ID` = `taskMetric`.`TASK_M_ID`)))
UNION ALL
SELECT
  concat(`taskMetric`.`TASK_M_ID`,'-',folderAudit.FLDR_A_ID) AS `ID`,
  `taskMetric`.`TASK_M_ID` AS `TASK_M_ID`,
  `taskMetric`.`R_TASK_T_ID` AS `R_TASK_T_ID`,
  `taskMetric`.`DOC_ID` AS `DOC_ID`,
  `taskMetric`.`FLDR_ID` AS `FLDR_ID`,
  folderAudit.FLDR_A_ID AS `A_ID`,
  NULL AS `ASSGN_ID`,
  folderAudit.FLDR_A_USER AS `A_USER`,
  folderAudit.FLDR_A_DT AS `A_DT`,
  folderAudit.R_FLDR_AUDIT_A_ID AS `R_AUDIT_A_ID`,
  folderAudit.FLDR_A_OLD_VAL AS `A_OLD_VAL`,
  folderAudit.FLDR_A_NEW_VAL AS `A_NEW_VAL`
FROM
  (`CTS_TASK_METRICS` `taskMetric` JOIN `CTS_FLDR_AUDIT` `folderAudit` ON ((`folderAudit`.`TASK_M_ID` = `taskMetric`.`TASK_M_ID`)))
UNION ALL
SELECT
  concat(`taskMetric`.`TASK_M_ID`,'-',assignAudit.ASSGN_A_ID ) AS `ID`,
  `taskMetric`.`TASK_M_ID` AS `TASK_M_ID`,
  `taskMetric`.`R_TASK_T_ID` AS `R_TASK_T_ID`,
  `taskMetric`.`DOC_ID` AS `DOC_ID`,
  `taskMetric`.`FLDR_ID` AS `FLDR_ID`,
  assignAudit.ASSGN_A_ID AS `AUDIT_ID`,
  assignAudit.ASSGN_ID AS `ASSGN_ID`,
  assignAudit.ASSGN_A_USER AS `A_USER`,
  assignAudit.ASSGN_A_DT AS `A_DT`,
  assignAudit.R_ASSGN_AUDIT_A_ID AS `R_AUDIT_A_ID`,
  assignAudit.ASSGN_A_OLD_VAL AS `A_OLD_VAL`,
  assignAudit.ASSGN_A_NEW_VAL AS `A_NEW_VAL`
FROM
  (`CTS_TASK_METRICS` `taskMetric` JOIN `CTS_ASSGN_AUDIT` `assignAudit` ON ((`assignAudit`.`TASK_M_ID` = `taskMetric`.`TASK_M_ID`))); 