-- --------------------------------------------------------

--
-- Table structure for table `SYS_AUDIT`
--

CREATE TABLE `SYS_AUDIT` (
  `AUDIT_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `PASS` tinyint(1) NOT NULL,
  `POC_USER_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_DAILY_USAGE`
--

CREATE TABLE `SYS_DAILY_USAGE` (
  `DAILY_USAGE_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `UNIQUE_USERS` int(11) DEFAULT NULL,
  `TOTAL_LOGINS` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_DOCUMENT`
--

CREATE TABLE `SYS_DOCUMENT` (
  `DOC_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `DOC_APPIAN_DOCUMENT_ID` int(11) NOT NULL,
  `DOC_CATEGORY_ID` int(11) NOT NULL,
  `DOC_DESCRIPTION` varchar(255) DEFAULT NULL,
  `DOC_UPLOADED_BY` varchar(255) DEFAULT NULL,
  `DOC_UPLOADED_DATETIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_ENVIRONMENT`
--

CREATE TABLE `SYS_ENVIRONMENT` (
  `ENVIRONMENT_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `RELEASE_ID` int(11) NOT NULL,
  `NAME` varchar(500) NOT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `IS_PROD` tinyint(1) DEFAULT NULL,
  `DEPLOY_ORDER` int(11) NOT NULL,
  `CREATED_BY` varchar(500) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(500) NOT NULL,
  `LAST_MODIFIED_DATETIME` datetime NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_HARDWARE`
--

CREATE TABLE `SYS_HARDWARE` (
  `HARDWARE_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `SERVER_NAME` varchar(255) NOT NULL,
  `OS` varchar(255) DEFAULT NULL,
  `CPU` varchar(255) DEFAULT NULL,
  `MEMORY` varchar(255) DEFAULT NULL,
  `DISK_SPACE` varchar(255) DEFAULT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_INTEGRATION`
--

CREATE TABLE `SYS_INTEGRATION` (
  `INTEGRATION_ID` int(11) NOT NULL,
  `SOURCE_SYSTEM_ID` int(11) NOT NULL,
  `DESTINATION_SYSTEM_ID` int(11) DEFAULT NULL,
  `IMPORTANCE_ID` int(11) NOT NULL,
  `READ_FROM_DEST` tinyint(1) DEFAULT NULL,
  `WRITE_TO_DEST` tinyint(1) DEFAULT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_ISSUE`
--

CREATE TABLE `SYS_ISSUE` (
  `ISSUE_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `AUDIT_ID` int(11) DEFAULT NULL,
  `TITLE` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(4000) NOT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `PRIORITY_ID` int(11) DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `REPORTED_BY_USER_ID` int(11) NOT NULL,
  `REPORTED_BY_DATETIME` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_OUTAGE`
--

CREATE TABLE `SYS_OUTAGE` (
  `OUTAGE_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `START_DATETIME` datetime DEFAULT NULL,
  `END_DATETIME` datetime DEFAULT NULL,
  `TYPE_ID` int(11) DEFAULT NULL,
  `REASON_ID` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DURATION` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `APN_FLDR_ID` int(11) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `PRIM_APPRVR` varchar(255) DEFAULT NULL,
  `PRIM_APPRVR_DTTM` datetime DEFAULT NULL,
  `SCND_APPRVR` varchar(255) DEFAULT NULL,
  `SCND_APPRVR_DTTM` datetime DEFAULT NULL,
  `PRIM_RSLVR` varchar(255) DEFAULT NULL,
  `PRIM_RSLVR_DTTM` datetime DEFAULT NULL,
  `SCND_RSLVR` varchar(255) DEFAULT NULL,
  `SCND_RSLVR_DTTM` datetime DEFAULT NULL,
  `NWS_EVNT_ID` varchar(255) NOT NULL COMMENT 'News Event Id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_OUTAGE_CMMNT`
--

CREATE TABLE `SYS_OUTAGE_CMMNT` (
  `CMMNT_ID` int(10) NOT NULL,
  `OUT_ID` int(10) DEFAULT NULL,
  `CMMNT_TXT` varchar(4000) DEFAULT NULL,
  `CMMNTD_BY` varchar(255) DEFAULT NULL,
  `CMMNTD_DTTM` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_OUTAGE_DOC`
--

CREATE TABLE `SYS_OUTAGE_DOC` (
  `FILE_ID` int(10) NOT NULL,
  `OUT_ID` int(10) DEFAULT NULL,
  `APN_DCMNT_ID` int(10) DEFAULT NULL,
  `FILE_NM` varchar(255) DEFAULT NULL,
  `FILE_SMMRY` varchar(4000) DEFAULT NULL,
  `FILE_ORD` int(10) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `CREATED_DTTM` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_POAM`
--

CREATE TABLE `SYS_POAM` (
  `POAM_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `CONTROLS` varchar(255) DEFAULT NULL,
  `WEAKNESS_NAME` varchar(255) DEFAULT NULL,
  `POC_USER_ID` int(11) DEFAULT NULL,
  `ORIGINAL_DETECTION_DATE` date DEFAULT NULL,
  `SCHEDULED_COMPLETION_DATE` date DEFAULT NULL,
  `PLANNED_MILESTONES` varchar(255) DEFAULT NULL,
  `MILESTONE_CHANGES` varchar(255) DEFAULT NULL,
  `STATUS_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_RELEASE`
--

CREATE TABLE `SYS_RELEASE` (
  `RELEASE_ID` int(11) NOT NULL,
  `SYSTEM_ID` int(11) NOT NULL,
  `VERSION` varchar(255) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DATE` date NOT NULL,
  `POC_USER_ID` int(11) DEFAULT NULL,
  `TYPE_ID` int(11) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT NULL,
  `NWS_EVNT_ID` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_R_DATA`
--

CREATE TABLE `SYS_R_DATA` (
  `ID` int(11) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `SYS_SYSTEM`
--

CREATE TABLE `SYS_SYSTEM` (
  `SYSTEM_ID` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `COMPLIANT` tinyint(1) DEFAULT NULL,
  `EXEC_SPONS_USER_ID` int(11) DEFAULT NULL,
  `BUS_OWNER_USER_ID` int(11) DEFAULT NULL,
  `IT_OWNER_USER_ID` int(11) DEFAULT NULL,
  `POC_USER_ID` int(11) DEFAULT NULL,
  `COOP_LAST_TEST_DATE` date DEFAULT NULL,
  `COOP_NEXT_TEST_DATE` date DEFAULT NULL,
  `POAM_SYS_IMPACT_LEVEL_ID` int(11) DEFAULT NULL,
  `KC_ID` int(10) DEFAULT NULL,
  `FLDR_ID` int(10) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `COOP_STATUS_ID` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `SYS_AUDIT`
--
ALTER TABLE `SYS_AUDIT`
  ADD PRIMARY KEY (`AUDIT_ID`),
  ADD KEY `FK_AUDIT_POC_USER_ID` (`POC_USER_ID`),
  ADD KEY `FK_AUDIT_SYSTEM_ID` (`SYSTEM_ID`);

--
-- Indexes for table `SYS_DAILY_USAGE`
--
ALTER TABLE `SYS_DAILY_USAGE`
  ADD PRIMARY KEY (`DAILY_USAGE_ID`),
  ADD KEY `FK_DAILY_USAGE_SYSTEM_ID` (`SYSTEM_ID`);

--
-- Indexes for table `SYS_DOCUMENT`
--
ALTER TABLE `SYS_DOCUMENT`
  ADD PRIMARY KEY (`DOC_ID`),
  ADD UNIQUE KEY `DOC_APPIAN_DOCUMENT_ID` (`DOC_APPIAN_DOCUMENT_ID`),
  ADD KEY `FK_DOC_CATEGORY_ID` (`DOC_CATEGORY_ID`),
  ADD KEY `SYSTEM_ID` (`SYSTEM_ID`);

--
-- Indexes for table `SYS_ENVIRONMENT`
--
ALTER TABLE `SYS_ENVIRONMENT`
  ADD PRIMARY KEY (`ENVIRONMENT_ID`),
  ADD UNIQUE KEY `UNIQUE_ROW` (`SYSTEM_ID`,`DEPLOY_ORDER`),
  ADD KEY `FK_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_RELEASE_ID` (`RELEASE_ID`);

--
-- Indexes for table `SYS_HARDWARE`
--
ALTER TABLE `SYS_HARDWARE`
  ADD PRIMARY KEY (`HARDWARE_ID`),
  ADD KEY `FK_HARDWARE_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_HARDWARE_TYPE_ID` (`TYPE_ID`);

--
-- Indexes for table `SYS_INTEGRATION`
--
ALTER TABLE `SYS_INTEGRATION`
  ADD PRIMARY KEY (`INTEGRATION_ID`),
  ADD KEY `FK_INTEGRATION_IMPORTANCE_ID` (`IMPORTANCE_ID`),
  ADD KEY `FK_INTEGRATION_SOURCE_SYSTEM_ID` (`SOURCE_SYSTEM_ID`) USING BTREE,
  ADD KEY `FK_INTEGRATION_TYPE_ID` (`TYPE_ID`),
  ADD KEY `FK_INTEGRATION_DESTINATION_SYSTEM_ID` (`DESTINATION_SYSTEM_ID`) USING BTREE;

--
-- Indexes for table `SYS_ISSUE`
--
ALTER TABLE `SYS_ISSUE`
  ADD PRIMARY KEY (`ISSUE_ID`),
  ADD KEY `FK_ISSUE_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_ISSUE_TYPE_ID` (`TYPE_ID`),
  ADD KEY `FK_ISSUE_STATUS_ID` (`STATUS_ID`),
  ADD KEY `FK_ISSUE_REPORTED_USER_ID` (`REPORTED_BY_USER_ID`),
  ADD KEY `FK_ISSUE_AUDIT_ID` (`AUDIT_ID`),
  ADD KEY `FK_ISSUE_PRIORITY_ID` (`PRIORITY_ID`);

--
-- Indexes for table `SYS_OUTAGE`
--
ALTER TABLE `SYS_OUTAGE`
  ADD PRIMARY KEY (`OUTAGE_ID`),
  ADD KEY `FK_OUTAGE_TYPE_ID` (`TYPE_ID`),
  ADD KEY `FK_OUTAGE_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_OUTAGE_REASON_ID` (`REASON_ID`);

--
-- Indexes for table `SYS_OUTAGE_CMMNT`
--
ALTER TABLE `SYS_OUTAGE_CMMNT`
  ADD PRIMARY KEY (`CMMNT_ID`);

--
-- Indexes for table `SYS_OUTAGE_DOC`
--
ALTER TABLE `SYS_OUTAGE_DOC`
  ADD PRIMARY KEY (`FILE_ID`);

--
-- Indexes for table `SYS_POAM`
--
ALTER TABLE `SYS_POAM`
  ADD PRIMARY KEY (`POAM_ID`),
  ADD KEY `FK_POAM_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_POAM_POC_USER_ID` (`POC_USER_ID`);

--
-- Indexes for table `SYS_RELEASE`
--
ALTER TABLE `SYS_RELEASE`
  ADD PRIMARY KEY (`RELEASE_ID`),
  ADD UNIQUE KEY `UNIQUE_RELEASE` (`SYSTEM_ID`,`DATE`),
  ADD KEY `FK_RELEASE_SYSTEM_ID` (`SYSTEM_ID`),
  ADD KEY `FK_RELEASE_POC_USER_ID` (`POC_USER_ID`),
  ADD KEY `FK_RELEASE_TYPE_ID` (`TYPE_ID`);

--
-- Indexes for table `SYS_R_DATA`
--
ALTER TABLE `SYS_R_DATA`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `SYS_SYSTEM`
--
ALTER TABLE `SYS_SYSTEM`
  ADD PRIMARY KEY (`SYSTEM_ID`),
  ADD KEY `FK_SYS_STATUS_ID` (`STATUS_ID`),
  ADD KEY `FK_SYS_EXEC_SPONS_USER_ID` (`EXEC_SPONS_USER_ID`),
  ADD KEY `FK_SYS_BUS_OWNER_USER_ID` (`BUS_OWNER_USER_ID`),
  ADD KEY `FK_SYS_IT_OWNER_USER_ID` (`IT_OWNER_USER_ID`),
  ADD KEY `FK_SYS_POC_USER_ID` (`POC_USER_ID`),
  ADD KEY `FK_SYS_SYS_IMPACT_ID` (`POAM_SYS_IMPACT_LEVEL_ID`),
  ADD KEY `FK_COOP_STATUS_ID` (`COOP_STATUS_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `SYS_AUDIT`
--
ALTER TABLE `SYS_AUDIT`
  MODIFY `AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
--
-- AUTO_INCREMENT for table `SYS_DAILY_USAGE`
--
ALTER TABLE `SYS_DAILY_USAGE`
  MODIFY `DAILY_USAGE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;
--
-- AUTO_INCREMENT for table `SYS_DOCUMENT`
--
ALTER TABLE `SYS_DOCUMENT`
  MODIFY `DOC_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
--
-- AUTO_INCREMENT for table `SYS_ENVIRONMENT`
--
ALTER TABLE `SYS_ENVIRONMENT`
  MODIFY `ENVIRONMENT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
--
-- AUTO_INCREMENT for table `SYS_HARDWARE`
--
ALTER TABLE `SYS_HARDWARE`
  MODIFY `HARDWARE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
--
-- AUTO_INCREMENT for table `SYS_INTEGRATION`
--
ALTER TABLE `SYS_INTEGRATION`
  MODIFY `INTEGRATION_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
--
-- AUTO_INCREMENT for table `SYS_ISSUE`
--
ALTER TABLE `SYS_ISSUE`
  MODIFY `ISSUE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT for table `SYS_OUTAGE`
--
ALTER TABLE `SYS_OUTAGE`
  MODIFY `OUTAGE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;
--
-- AUTO_INCREMENT for table `SYS_OUTAGE_CMMNT`
--
ALTER TABLE `SYS_OUTAGE_CMMNT`
  MODIFY `CMMNT_ID` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
--
-- AUTO_INCREMENT for table `SYS_OUTAGE_DOC`
--
ALTER TABLE `SYS_OUTAGE_DOC`
  MODIFY `FILE_ID` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
--
-- AUTO_INCREMENT for table `SYS_POAM`
--
ALTER TABLE `SYS_POAM`
  MODIFY `POAM_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
--
-- AUTO_INCREMENT for table `SYS_RELEASE`
--
ALTER TABLE `SYS_RELEASE`
  MODIFY `RELEASE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=85;
--
-- AUTO_INCREMENT for table `SYS_SYSTEM`
--
ALTER TABLE `SYS_SYSTEM`
  MODIFY `SYSTEM_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `SYS_AUDIT`
--
ALTER TABLE `SYS_AUDIT`
  ADD CONSTRAINT `FK_AUDIT_POC_USER_ID` FOREIGN KEY (`POC_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_AUDIT_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`);

--
-- Constraints for table `SYS_DAILY_USAGE`
--
ALTER TABLE `SYS_DAILY_USAGE`
  ADD CONSTRAINT `FK_DAILY_USAGE_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`);

--
-- Constraints for table `SYS_DOCUMENT`
--
ALTER TABLE `SYS_DOCUMENT`
  ADD CONSTRAINT `FK_DOCUMENT_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_DOC_CATEGORY_ID` FOREIGN KEY (`DOC_CATEGORY_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_ENVIRONMENT`
--
ALTER TABLE `SYS_ENVIRONMENT`
  ADD CONSTRAINT `FK_ENV_RELEASE_ID` FOREIGN KEY (`RELEASE_ID`) REFERENCES `SYS_RELEASE` (`RELEASE_ID`),
  ADD CONSTRAINT `FK_ENV_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`);

--
-- Constraints for table `SYS_HARDWARE`
--
ALTER TABLE `SYS_HARDWARE`
  ADD CONSTRAINT `FK_HARDWARE_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_HARDWARE_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_INTEGRATION`
--
ALTER TABLE `SYS_INTEGRATION`
  ADD CONSTRAINT `FK_INTEGRATION_DESTINATION_SYSTEM_ID` FOREIGN KEY (`DESTINATION_SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_INTEGRATION_IMPORTANCE_ID` FOREIGN KEY (`IMPORTANCE_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_INTEGRATION_SOURCE_SYSTEM_ID` FOREIGN KEY (`SOURCE_SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_INTEGRATION_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_ISSUE`
--
ALTER TABLE `SYS_ISSUE`
  ADD CONSTRAINT `FK_ISSUE_AUDIT_ID` FOREIGN KEY (`AUDIT_ID`) REFERENCES `SYS_AUDIT` (`AUDIT_ID`),
  ADD CONSTRAINT `FK_ISSUE_PRIORITY_ID` FOREIGN KEY (`PRIORITY_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_ISSUE_REPORTED_USER_ID` FOREIGN KEY (`REPORTED_BY_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_ISSUE_STATUS_ID` FOREIGN KEY (`STATUS_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_ISSUE_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_ISSUE_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_OUTAGE`
--
ALTER TABLE `SYS_OUTAGE`
  ADD CONSTRAINT `FK_OUTAGE_REASON_ID` FOREIGN KEY (`REASON_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_OUTAGE_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_OUTAGE_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_POAM`
--
ALTER TABLE `SYS_POAM`
  ADD CONSTRAINT `FK_POAM_POC_USER_ID` FOREIGN KEY (`POC_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_POAM_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`);

--
-- Constraints for table `SYS_RELEASE`
--
ALTER TABLE `SYS_RELEASE`
  ADD CONSTRAINT `FK_RELEASE_POC_USER_ID` FOREIGN KEY (`POC_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_RELEASE_SYSTEM_ID` FOREIGN KEY (`SYSTEM_ID`) REFERENCES `SYS_SYSTEM` (`SYSTEM_ID`),
  ADD CONSTRAINT `FK_RELEASE_TYPE_ID` FOREIGN KEY (`TYPE_ID`) REFERENCES `SYS_R_DATA` (`ID`);

--
-- Constraints for table `SYS_SYSTEM`
--
ALTER TABLE `SYS_SYSTEM`
  ADD CONSTRAINT `FK_COOP_STATUS_ID` FOREIGN KEY (`COOP_STATUS_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_SYS_BUS_OWNER_USER_ID` FOREIGN KEY (`BUS_OWNER_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_SYS_EXEC_SPONS_USER_ID` FOREIGN KEY (`EXEC_SPONS_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_SYS_IT_OWNER_USER_ID` FOREIGN KEY (`IT_OWNER_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_SYS_POC_USER_ID` FOREIGN KEY (`POC_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_SYS_STATUS_ID` FOREIGN KEY (`STATUS_ID`) REFERENCES `SYS_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_SYS_SYS_IMPACT_ID` FOREIGN KEY (`POAM_SYS_IMPACT_LEVEL_ID`) REFERENCES `SYS_R_DATA` (`ID`);