-- --------------------------------------------------------

--
-- Table structure for table `HR_BKGD_INV`
--

CREATE TABLE `HR_BKGD_INV` (
  `BKGDINV_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `BKGDINV_TYPE_ID` int(11) DEFAULT NULL,
  `BKGDINV_INVGTR` varchar(255) DEFAULT NULL,
  `BKGDINV_COMMENTS` varchar(4000) DEFAULT NULL,
  `BKGDINV_TTL_SEV_ID` int(11) DEFAULT NULL,
  `BKGDINV_APPN_FLDR_ID` int(11) DEFAULT NULL,
  `BKGDINV_STATUS_ID` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `COMPLETED_BY` varchar(255) DEFAULT NULL,
  `COMPLETED_DATETIME` datetime DEFAULT NULL,
  `BKGDINV_ADJTN_COMMENTS` varchar(4000) DEFAULT NULL,
  `BKGDINV_ADJTN_ID` int(11) DEFAULT NULL,
  `BKGDINV_ADJTN_END_DATE` date DEFAULT NULL,
  `BKGDINV_ADJTN_BY` varchar(255) DEFAULT NULL,
  `BKGDINV_ADJTN_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_BKGD_INV_ISSUE`
--

CREATE TABLE `HR_BKGD_INV_ISSUE` (
  `BKGDINV_ID` int(11) NOT NULL,
  `BKGDINV_ISSUE_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_BUILDING`
--

CREATE TABLE `HR_BUILDING` (
  `BUILDING_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `LEASE_FROM_DATE` date DEFAULT NULL,
  `LEASE_TO_DATE` date DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `SELL_DATE` date DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(255) DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `ADDRESS_LINE_3` varchar(255) DEFAULT NULL,
  `PHONE_NUMBER` varchar(255) DEFAULT NULL,
  `CODE` varchar(255) DEFAULT NULL,
  `SQUARE_FEET` int(11) DEFAULT NULL,
  `CAMPUS_ID` int(11) DEFAULT NULL,
  `BUILDING_PHOTO` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `HAS_PARKING` tinyint(1) DEFAULT NULL,
  `FREE_PARKING` tinyint(1) DEFAULT NULL,
  `HAS_FRONT_DESK` tinyint(1) DEFAULT NULL,
  `HAS_CAFETERIA` tinyint(1) DEFAULT NULL,
  `HAS_GYM` tinyint(1) DEFAULT NULL,
  `BADGE_REQUIRED` tinyint(1) DEFAULT NULL,
  `IS_LEASED` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_BUILDING_AUDIT`
--

CREATE TABLE `HR_BUILDING_AUDIT` (
  `BUILDING_AUDIT_ID` int(11) NOT NULL,
  `BUILDING_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `BUILDING_AUDIT_ACTION_ID` int(11) NOT NULL,
  `BUILDING_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `BUILDING_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `BUILDING_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_CAMPUS`
--

CREATE TABLE `HR_CAMPUS` (
  `CAMPUS_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `ZIP` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_CAMPUS_AUDIT`
--

CREATE TABLE `HR_CAMPUS_AUDIT` (
  `CAMPUS_AUDIT_ID` int(11) NOT NULL,
  `CAMPUS_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `CAMPUS_AUDIT_ACTION_ID` int(11) NOT NULL,
  `CAMPUS_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `CAMPUS_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `CAMPUS_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_FLOOR`
--

CREATE TABLE `HR_FLOOR` (
  `FLOOR_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `BUILDING_ID` int(11) DEFAULT NULL,
  `FLOOR_PLAN` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `OPEN_FLOOR_PLAN` tinyint(1) NOT NULL,
  `QUIET_AREA_ONLY` tinyint(1) NOT NULL,
  `HAS_KITCHEN` tinyint(1) NOT NULL,
  `HAS_COMMON_AREA` tinyint(1) NOT NULL,
  `BADGE_REQUIRED` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_FLOOR_AUDIT`
--

CREATE TABLE `HR_FLOOR_AUDIT` (
  `FLOOR_AUDIT_ID` int(11) NOT NULL,
  `FLOOR_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `FLOOR_AUDIT_ACTION_ID` int(11) NOT NULL,
  `FLOOR_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `FLOOR_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `FLOOR_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_IT_EQUIPMENT`
--

CREATE TABLE `HR_IT_EQUIPMENT` (
  `IT_EQUIPMENT_ID` int(11) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `IT_EQUIPMENT_TYPE_ID` int(11) DEFAULT NULL,
  `SERIAL_NUMBER` varchar(255) DEFAULT NULL,
  `MAKE` varchar(255) DEFAULT NULL,
  `MODEL` varchar(255) DEFAULT NULL,
  `IS_LEASED` tinyint(1) DEFAULT NULL,
  `LEASE_FROM_DATE` date DEFAULT NULL,
  `LEASE_TO_DATE` date DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `END_OF_LIFE_DATE` date DEFAULT NULL,
  `ASSIGNED_DATE` date DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `MEMORY` varchar(500) DEFAULT NULL,
  `HD_SIZE` varchar(500) DEFAULT NULL,
  `PROCESSOR` varchar(500) DEFAULT NULL,
  `PURCHASE_TYPE` varchar(500) DEFAULT NULL,
  `LEASE_NUMBER` varchar(500) DEFAULT NULL,
  `ORDER_NUMBER` varchar(500) DEFAULT NULL,
  `EXPENSE_NUMBER` varchar(500) DEFAULT NULL,
  `WARRANTY_END_DATE` date DEFAULT NULL,
  `WARRANTY_TYPE` varchar(500) DEFAULT NULL,
  `USER_ASSIGNED` varchar(500) DEFAULT NULL,
  `ROOM_ASSIGNED` varchar(500) DEFAULT NULL,
  `COUNTRY` varchar(500) DEFAULT NULL,
  `LOCATION` varchar(500) DEFAULT NULL,
  `USER_DEPARTMENT` varchar(500) DEFAULT NULL,
  `USER_MANAGER` varchar(500) DEFAULT NULL,
  `STATUS` varchar(500) DEFAULT NULL,
  `IS_PORTABLE` tinyint(1) DEFAULT NULL,
  `MONITOR_SIZE` varchar(500) DEFAULT NULL,
  `NOTES` varchar(500) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_IT_EQUIPMENT_AUDIT`
--

CREATE TABLE `HR_IT_EQUIPMENT_AUDIT` (
  `IT_EQUIPMENT_AUDIT_ID` int(11) NOT NULL,
  `IT_EQUIPMENT_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `IT_EQUIPMENT_AUDIT_ACTION_ID` int(11) NOT NULL,
  `IT_EQUIPMENT_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `IT_EQUIPMENT_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `IT_EQUIPMENT_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_L_USER_TRAINING`
--

CREATE TABLE `HR_L_USER_TRAINING` (
  `USER_TRAINING_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `TRAINING_ID` int(11) NOT NULL,
  `FEEDBACK_RATING` int(11) DEFAULT NULL,
  `FEEDBACK_COMMENT` varchar(255) DEFAULT NULL,
  `COMPLETED_DTTM` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_POSTN`
--

CREATE TABLE `HR_POSTN` (
  `POSTN_ID` int(11) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_ID` int(11) NOT NULL,
  `POSTN_NM` varchar(255) DEFAULT NULL,
  `OPEN_DATE` date DEFAULT NULL,
  `CLOSE_DATE` date DEFAULT NULL,
  `STATUS_ID` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_POSTN_AUDIT`
--

CREATE TABLE `HR_POSTN_AUDIT` (
  `POSTN_AUDIT_ID` int(11) NOT NULL,
  `POSTN_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `POSTN_AUDIT_ACTION_ID` int(11) NOT NULL,
  `POSTN_AUDIT_OLD_VALUE` varchar(2000) DEFAULT NULL,
  `POSTN_AUDIT_NEW_VALUE` varchar(2000) DEFAULT NULL,
  `POSTN_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_POSTN_DESC`
--

CREATE TABLE `HR_POSTN_DESC` (
  `POSTN_DESC_ID` int(11) NOT NULL,
  `POSTN_DESC_NAME` varchar(255) NOT NULL,
  `POSTN_DESC` varchar(255) DEFAULT NULL,
  `POSTN_DESC_GRADE` varchar(255) DEFAULT NULL,
  `POSTN_DESC_SERIES` varchar(255) DEFAULT NULL,
  `DEPT_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_SALARY_LOWER` decimal(19,2) DEFAULT NULL,
  `POSTN_DESC_SALARY_UPPER` decimal(19,2) DEFAULT NULL,
  `SALARY_FREQUENCY_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_LOCATION` varchar(255) DEFAULT NULL,
  `POSTN_DESC_ANNOUNCEMENT` varchar(255) DEFAULT NULL,
  `AGENCY_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_INFO` varchar(255) DEFAULT NULL,
  `ELIGIBILITY_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_SUPERVISORY_STATUS` tinyint(1) DEFAULT NULL,
  `POSTN_DESC_PROMOTION_POTENTIAL` int(11) DEFAULT NULL,
  `POSTN_DESC_CONTROL_NUMBER` varchar(255) DEFAULT NULL,
  `POSTN_DESC_SUMMARY` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_DUTIES` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_TRAVEL_PERCENTAGE` int(11) DEFAULT NULL,
  `POSTN_DESC_RELOCATION_AUTHORIZED` tinyint(1) DEFAULT NULL,
  `POSTN_DESC_KEY_REQUIREMENTS` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_QUALIFICATIONS` varchar(2000) DEFAULT NULL,
  `SECURITY_CLEARANCE_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_NEXT_STEPS` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_BENEFITS` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_OTHER_INFO` varchar(2000) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_POSTN_DESC_AUDIT`
--

CREATE TABLE `HR_POSTN_DESC_AUDIT` (
  `POSTN_DESC_AUDIT_ID` int(11) NOT NULL,
  `POSTN_DESC_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `POSTN_DESC_AUDIT_ACTION_ID` int(11) NOT NULL,
  `POSTN_DESC_AUDIT_OLD_VALUE` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_AUDIT_NEW_VALUE` varchar(2000) DEFAULT NULL,
  `POSTN_DESC_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_RESERVATION`
--

CREATE TABLE `HR_RESERVATION` (
  `RESERVATION_ID` int(11) NOT NULL,
  `SPACE_ID` int(11) NOT NULL,
  `RESERVATION_USER_ID` int(11) NOT NULL,
  `RESERVATION_FROM` datetime NOT NULL,
  `RESERVATION_TO` datetime NOT NULL,
  `RESERVATION_DURN` decimal(19,2) DEFAULT NULL,
  `RESERVATION_NUM_OF_ATTENDEES` int(11) DEFAULT NULL,
  `RESERVATION_REPEAT` tinyint(1) DEFAULT NULL,
  `RESERVATION_REPEAT_TYPE` int(11) DEFAULT NULL,
  `RESERVATION_REPEAT_EVERY` int(11) DEFAULT NULL,
  `RESERVATION_REPEAT_ENDS` int(11) DEFAULT NULL,
  `RESERVATION_REPEAT_OCCUR` int(11) DEFAULT NULL,
  `RESERVATION_REPEAT_DATE` date DEFAULT NULL,
  `RESERVATION_REPEAT_ON` varchar(255) DEFAULT NULL,
  `RESERVATION_REPEAT_BY` int(11) DEFAULT NULL,
  `ORIG_RESERVATION_ID` int(11) DEFAULT NULL,
  `RESERVATION_CHECK_IN` datetime DEFAULT NULL,
  `RESERVATION_CHECK_OUT` datetime DEFAULT NULL,
  `IS_APPROVED` tinyint(1) NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_RESERVATION_AUDIT`
--

CREATE TABLE `HR_RESERVATION_AUDIT` (
  `RESERVATION_AUDIT_ID` int(11) NOT NULL,
  `RESERVATION_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `RESERVATION_AUDIT_ACTION_ID` int(11) NOT NULL,
  `RESERVATION_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `RESERVATION_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `RESERVATION_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_BUILDING_AUDIT_ACTION`
--

CREATE TABLE `HR_R_BUILDING_AUDIT_ACTION` (
  `BUILDING_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_CAMPUS_AUDIT_ACTION`
--

CREATE TABLE `HR_R_CAMPUS_AUDIT_ACTION` (
  `CAMPUS_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_DATA`
--

CREATE TABLE `HR_R_DATA` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `TYPE` varchar(255) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_DEPT`
--

CREATE TABLE `HR_R_DEPT` (
  `DEPT_ID` int(11) NOT NULL,
  `DEPT_NM` varchar(255) DEFAULT NULL,
  `PARENT_DEPT_ID` int(11) DEFAULT NULL,
  `MAIN_PARENT_DEPT_ID` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_FLOOR_AUDIT_ACTION`
--

CREATE TABLE `HR_R_FLOOR_AUDIT_ACTION` (
  `FLOOR_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_IT_EQUIPMENT_AUDIT_ACTION`
--

CREATE TABLE `HR_R_IT_EQUIPMENT_AUDIT_ACTION` (
  `IT_EQUIPMENT_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_POSTN_AUDIT_ACTION`
--

CREATE TABLE `HR_R_POSTN_AUDIT_ACTION` (
  `POSTN_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_POSTN_DESC_AUDIT_ACTION`
--

CREATE TABLE `HR_R_POSTN_DESC_AUDIT_ACTION` (
  `POSTN_DESC_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_RESERVATION_AUDIT_ACTION`
--

CREATE TABLE `HR_R_RESERVATION_AUDIT_ACTION` (
  `RESERVATION_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_SPACE_AUDIT_ACTION`
--

CREATE TABLE `HR_R_SPACE_AUDIT_ACTION` (
  `SPACE_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_TRAINING_AUDIT_ACTION`
--

CREATE TABLE `HR_R_TRAINING_AUDIT_ACTION` (
  `TRAINING_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_USER_AUDIT_ACTION`
--

CREATE TABLE `HR_R_USER_AUDIT_ACTION` (
  `USER_AUDIT_ACTION_ID` int(11) NOT NULL,
  `LABEL` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_R_WORKFLOW_TASK_TYPE`
--

CREATE TABLE `HR_R_WORKFLOW_TASK_TYPE` (
  `TASK_TYPE_ID` int(11) NOT NULL,
  `WORKFLOW_TYPE_ID` int(11) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `TASK_ORDER` int(11) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_SPACE`
--

CREATE TABLE `HR_SPACE` (
  `SPACE_ID` int(11) NOT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `SPACE_TYPE_ID` int(11) DEFAULT NULL,
  `IS_TEMP_SPACE` tinyint(1) DEFAULT NULL,
  `FLOOR_ID` int(11) DEFAULT NULL,
  `NEEDS_APPROVAL` tinyint(1) NOT NULL,
  `CAPACITY` int(11) DEFAULT NULL,
  `AV_EQUIPMENT` tinyint(1) DEFAULT NULL,
  `DUAL_MONITORS` tinyint(1) DEFAULT NULL,
  `DOCKING_STATION` tinyint(1) DEFAULT NULL,
  `KEYBOARD` tinyint(1) DEFAULT NULL,
  `MOUSE` tinyint(1) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_SPACE_AUDIT`
--

CREATE TABLE `HR_SPACE_AUDIT` (
  `SPACE_AUDIT_ID` int(11) NOT NULL,
  `SPACE_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `SPACE_AUDIT_ACTION_ID` int(11) NOT NULL,
  `SPACE_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `SPACE_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `SPACE_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_TRAINING`
--

CREATE TABLE `HR_TRAINING` (
  `TRAINING_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `IS_MANDATORY` tinyint(1) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `AVAILABLE_DATE` date NOT NULL,
  `DUE_DATE` date NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_TRAINING_AUDIT`
--

CREATE TABLE `HR_TRAINING_AUDIT` (
  `TRAINING_AUDIT_ID` int(11) NOT NULL,
  `TRAINING_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `TRAINING_AUDIT_ACTION_ID` int(11) NOT NULL,
  `TRAINING_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `TRAINING_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `TRAINING_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_USER`
--

CREATE TABLE `HR_USER` (
  `USER_ID` int(11) NOT NULL,
  `AF_USER_ID` int(11) NOT NULL,
  `USER_STATUS_ID` int(11) DEFAULT NULL,
  `USER_HIRE_DT` date DEFAULT NULL,
  `USER_SPRV_ID` int(11) DEFAULT NULL,
  `USER_TYPE_ID` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `LAST_MODIFIED_BY` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_DATETIME` datetime DEFAULT NULL,
  `APPROVED_BY` varchar(255) DEFAULT NULL,
  `APPROVED_DATETIME` datetime DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  `USER_SUFFIX` varchar(255) DEFAULT NULL,
  `USER_SSN` varchar(255) DEFAULT NULL,
  `USER_TAX_ID` varchar(255) DEFAULT NULL,
  `USER_FOREIGN_ID` varchar(255) DEFAULT NULL,
  `USER_BIRTH_DATE` date DEFAULT NULL,
  `USER_BIRTH_COUNTRY` varchar(255) DEFAULT NULL,
  `USER_BIRTH_STATE` varchar(255) DEFAULT NULL,
  `USER_BIRTH_CITY` varchar(255) DEFAULT NULL,
  `USER_CITZ_COUNTRY` varchar(255) DEFAULT NULL,
  `USER_IS_US_CITZ` tinyint(1) DEFAULT NULL,
  `USER_PERSONAL_EMAIL` varchar(255) DEFAULT NULL,
  `USER_CONTRACT_VENDOR` varchar(255) DEFAULT NULL,
  `USER_CONTRACT_PM_EMAIL` varchar(255) DEFAULT NULL,
  `USER_CONTRACTOR_EMPLOYER` varchar(255) DEFAULT NULL,
  `USER_CONTRACT_OFFICER_NAME` varchar(255) DEFAULT NULL,
  `USER_CONTRACT_NUMBER` varchar(255) DEFAULT NULL,
  `USER_CONTRACT_POP_START` date DEFAULT NULL,
  `USER_CONTRACT_POP_END` date DEFAULT NULL,
  `USER_TASK_ORDER_NUMBER` varchar(255) DEFAULT NULL,
  `USER_TASK_ORDER_POP_START` date DEFAULT NULL,
  `USER_TASK_ORDER_POP_END` date DEFAULT NULL,
  `APPIAN_FOLDER_ID` int(11) NOT NULL,
  `ONBOARDING_WORKFLOW_ID` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_USER_AUDIT`
--

CREATE TABLE `HR_USER_AUDIT` (
  `USER_AUDIT_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `USER_AUDIT_ACTION_ID` int(11) NOT NULL,
  `USER_AUDIT_OLD_VALUE` varchar(255) DEFAULT NULL,
  `USER_AUDIT_NEW_VALUE` varchar(255) DEFAULT NULL,
  `USER_AUDIT_DATETIME` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_WORKFLOW`
--

CREATE TABLE `HR_WORKFLOW` (
  `WORKFLOW_ID` int(11) NOT NULL,
  `WF_APPIAN_PROCESS_ID` int(11) DEFAULT NULL,
  `WF_START_DATETIME` datetime DEFAULT NULL,
  `WF_END_DATETIME` datetime DEFAULT NULL,
  `WORKFLOW_TYPE_ID` int(11) DEFAULT NULL,
  `WORKFLOW_STATUS_ID` int(11) DEFAULT NULL,
  `CURRENT_TASK_TYPE_ID` int(11) DEFAULT NULL,
  `WF_STARTED_BY` varchar(255) DEFAULT NULL,
  `WF_APPIAN_FOLDER_ID` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_WORKFLOW_COMMENT`
--

CREATE TABLE `HR_WORKFLOW_COMMENT` (
  `COMMENT_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `COMMENT_TEXT` varchar(4000) DEFAULT NULL,
  `COMMENT_BY` varchar(255) DEFAULT NULL,
  `COMMENT_DATETIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_WORKFLOW_DOCUMENT`
--

CREATE TABLE `HR_WORKFLOW_DOCUMENT` (
  `DOC_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `DOC_APPIAN_DOCUMENT_ID` int(11) DEFAULT NULL,
  `DOC_DESCRIPTION` varchar(255) DEFAULT NULL,
  `DOC_UPLOADED_BY` varchar(255) DEFAULT NULL,
  `DOC_UPLOADED_DATETIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `HR_WORKFLOW_TASK`
--

CREATE TABLE `HR_WORKFLOW_TASK` (
  `TASK_ID` int(11) NOT NULL,
  `WORKFLOW_ID` int(11) DEFAULT NULL,
  `TASK_TYPE_ID` int(11) DEFAULT NULL,
  `TASK_APPIAN_TASK_ID` int(11) DEFAULT NULL,
  `TASK_START_DATETIME` datetime DEFAULT NULL,
  `TASK_ACCEPT_DATETIME` datetime DEFAULT NULL,
  `TASK_END_DATETIME` datetime DEFAULT NULL,
  `TASK_ASSIGNEE_USERS` varchar(4000) DEFAULT NULL,
  `TASK_ASSIGNEE_GROUPS` varchar(4000) DEFAULT NULL,
  `TASK_OWNER` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `HR_BKGD_INV`
--
ALTER TABLE `HR_BKGD_INV`
  ADD PRIMARY KEY (`BKGDINV_ID`),
  ADD KEY `FK_BKGD_INV_TYPE_ID` (`BKGDINV_TYPE_ID`),
  ADD KEY `FK_BKGD_INV_TTL_SEV_ID` (`BKGDINV_TTL_SEV_ID`),
  ADD KEY `FK_BKGD_INV_STATUS_ID` (`BKGDINV_STATUS_ID`),
  ADD KEY `FK_BKGD_INV_ADJTN_ID` (`BKGDINV_ADJTN_ID`),
  ADD KEY `FK_BKGD_INV_USER_ID` (`USER_ID`);

--
-- Indexes for table `HR_BKGD_INV_ISSUE`
--
ALTER TABLE `HR_BKGD_INV_ISSUE`
  ADD KEY `FK_BKGD_INV_ID` (`BKGDINV_ID`),
  ADD KEY `FK_BKGD_INV_ISSUE_ID` (`BKGDINV_ISSUE_ID`);

--
-- Indexes for table `HR_BUILDING`
--
ALTER TABLE `HR_BUILDING`
  ADD PRIMARY KEY (`BUILDING_ID`),
  ADD KEY `	CAMPUS_ID` (`CAMPUS_ID`);

--
-- Indexes for table `HR_BUILDING_AUDIT`
--
ALTER TABLE `HR_BUILDING_AUDIT`
  ADD PRIMARY KEY (`BUILDING_AUDIT_ID`),
  ADD KEY `FK_BUILDING_ID` (`BUILDING_ID`),
  ADD KEY `fk_BuildingAuditActionId` (`BUILDING_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_CAMPUS`
--
ALTER TABLE `HR_CAMPUS`
  ADD PRIMARY KEY (`CAMPUS_ID`);

--
-- Indexes for table `HR_CAMPUS_AUDIT`
--
ALTER TABLE `HR_CAMPUS_AUDIT`
  ADD PRIMARY KEY (`CAMPUS_AUDIT_ID`),
  ADD KEY `FK_CAMPUS_ID` (`CAMPUS_ID`),
  ADD KEY `fk_CampusAuditActionId` (`CAMPUS_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_FLOOR`
--
ALTER TABLE `HR_FLOOR`
  ADD PRIMARY KEY (`FLOOR_ID`),
  ADD KEY `BUILDING_ID` (`BUILDING_ID`);

--
-- Indexes for table `HR_FLOOR_AUDIT`
--
ALTER TABLE `HR_FLOOR_AUDIT`
  ADD PRIMARY KEY (`FLOOR_AUDIT_ID`),
  ADD KEY `FK_FLOOR_ID` (`FLOOR_ID`),
  ADD KEY `fk_FloorAuditActionId` (`FLOOR_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_IT_EQUIPMENT`
--
ALTER TABLE `HR_IT_EQUIPMENT`
  ADD PRIMARY KEY (`IT_EQUIPMENT_ID`),
  ADD KEY `FK_IT_EQUIP_EQUIP_TYPE` (`IT_EQUIPMENT_TYPE_ID`),
  ADD KEY `FK_IT_EQUIP_USER_ID` (`USER_ID`) USING BTREE;

--
-- Indexes for table `HR_IT_EQUIPMENT_AUDIT`
--
ALTER TABLE `HR_IT_EQUIPMENT_AUDIT`
  ADD PRIMARY KEY (`IT_EQUIPMENT_AUDIT_ID`),
  ADD KEY `FK_IT_EQUIPMENT_ID` (`IT_EQUIPMENT_ID`),
  ADD KEY `fk_ItEquipmentAuditActionId` (`IT_EQUIPMENT_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_L_USER_TRAINING`
--
ALTER TABLE `HR_L_USER_TRAINING`
  ADD PRIMARY KEY (`USER_TRAINING_ID`),
  ADD KEY `USER_ID_INDEX` (`USER_ID`),
  ADD KEY `TRAINING_ID_INDEX` (`TRAINING_ID`) USING BTREE;

--
-- Indexes for table `HR_POSTN`
--
ALTER TABLE `HR_POSTN`
  ADD PRIMARY KEY (`POSTN_ID`),
  ADD KEY `POSTN_USER_ID` (`USER_ID`),
  ADD KEY `FK_STATUS_ID` (`STATUS_ID`),
  ADD KEY `FK_POSTN_DESC_ID` (`POSTN_DESC_ID`);

--
-- Indexes for table `HR_POSTN_AUDIT`
--
ALTER TABLE `HR_POSTN_AUDIT`
  ADD PRIMARY KEY (`POSTN_AUDIT_ID`),
  ADD KEY `FK_HR_POSTN_ID_AUDIT` (`POSTN_ID`),
  ADD KEY `FK_HR_POSTN_AUDIT_WORKFLOW_ID` (`WORKFLOW_ID`),
  ADD KEY `fk_PostnAuditActionId` (`POSTN_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_POSTN_DESC`
--
ALTER TABLE `HR_POSTN_DESC`
  ADD PRIMARY KEY (`POSTN_DESC_ID`),
  ADD KEY `FK_DEPT_ID` (`DEPT_ID`) USING BTREE,
  ADD KEY `FK_ELIGIBILITY_ID` (`ELIGIBILITY_ID`) USING BTREE,
  ADD KEY `FK_AGENCY_ID` (`AGENCY_ID`) USING BTREE,
  ADD KEY `fk_postn_salary_freq` (`SALARY_FREQUENCY_ID`),
  ADD KEY `fk_postn_security_clearance` (`SECURITY_CLEARANCE_ID`);

--
-- Indexes for table `HR_POSTN_DESC_AUDIT`
--
ALTER TABLE `HR_POSTN_DESC_AUDIT`
  ADD PRIMARY KEY (`POSTN_DESC_AUDIT_ID`),
  ADD KEY `FK_HR_POSTN_DESC_ID_AUDIT` (`POSTN_DESC_ID`),
  ADD KEY `FK_HR_POSTN_DESC_AUDIT_WORKFLOW_ID` (`WORKFLOW_ID`),
  ADD KEY `fk_PostnDescAuditActionId` (`POSTN_DESC_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_RESERVATION`
--
ALTER TABLE `HR_RESERVATION`
  ADD PRIMARY KEY (`RESERVATION_ID`),
  ADD KEY `SPACE_ID_FK` (`SPACE_ID`) USING BTREE,
  ADD KEY `RESERVATION_USER_ID_FK` (`RESERVATION_USER_ID`) USING BTREE,
  ADD KEY `ORG_RES_ID` (`ORIG_RESERVATION_ID`);

--
-- Indexes for table `HR_RESERVATION_AUDIT`
--
ALTER TABLE `HR_RESERVATION_AUDIT`
  ADD PRIMARY KEY (`RESERVATION_AUDIT_ID`),
  ADD KEY `FK_RESERVATION_ID` (`RESERVATION_ID`),
  ADD KEY `fk_ReservationAuditActionId` (`RESERVATION_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_BUILDING_AUDIT_ACTION`
--
ALTER TABLE `HR_R_BUILDING_AUDIT_ACTION`
  ADD PRIMARY KEY (`BUILDING_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_CAMPUS_AUDIT_ACTION`
--
ALTER TABLE `HR_R_CAMPUS_AUDIT_ACTION`
  ADD PRIMARY KEY (`CAMPUS_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_DATA`
--
ALTER TABLE `HR_R_DATA`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `HR_R_DEPT`
--
ALTER TABLE `HR_R_DEPT`
  ADD PRIMARY KEY (`DEPT_ID`);

--
-- Indexes for table `HR_R_FLOOR_AUDIT_ACTION`
--
ALTER TABLE `HR_R_FLOOR_AUDIT_ACTION`
  ADD PRIMARY KEY (`FLOOR_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_IT_EQUIPMENT_AUDIT_ACTION`
--
ALTER TABLE `HR_R_IT_EQUIPMENT_AUDIT_ACTION`
  ADD PRIMARY KEY (`IT_EQUIPMENT_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_POSTN_AUDIT_ACTION`
--
ALTER TABLE `HR_R_POSTN_AUDIT_ACTION`
  ADD PRIMARY KEY (`POSTN_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_POSTN_DESC_AUDIT_ACTION`
--
ALTER TABLE `HR_R_POSTN_DESC_AUDIT_ACTION`
  ADD PRIMARY KEY (`POSTN_DESC_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_RESERVATION_AUDIT_ACTION`
--
ALTER TABLE `HR_R_RESERVATION_AUDIT_ACTION`
  ADD PRIMARY KEY (`RESERVATION_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_SPACE_AUDIT_ACTION`
--
ALTER TABLE `HR_R_SPACE_AUDIT_ACTION`
  ADD PRIMARY KEY (`SPACE_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_TRAINING_AUDIT_ACTION`
--
ALTER TABLE `HR_R_TRAINING_AUDIT_ACTION`
  ADD PRIMARY KEY (`TRAINING_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_USER_AUDIT_ACTION`
--
ALTER TABLE `HR_R_USER_AUDIT_ACTION`
  ADD PRIMARY KEY (`USER_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_R_WORKFLOW_TASK_TYPE`
--
ALTER TABLE `HR_R_WORKFLOW_TASK_TYPE`
  ADD PRIMARY KEY (`TASK_TYPE_ID`),
  ADD UNIQUE KEY `TASK_TYPE_UNQ` (`WORKFLOW_TYPE_ID`,`TASK_ORDER`);

--
-- Indexes for table `HR_SPACE`
--
ALTER TABLE `HR_SPACE`
  ADD PRIMARY KEY (`SPACE_ID`),
  ADD KEY `SPACE_TYPE_ID` (`SPACE_TYPE_ID`),
  ADD KEY `FLOOR_ID` (`FLOOR_ID`),
  ADD KEY `FK_SPACE_USER_ID` (`USER_ID`);

--
-- Indexes for table `HR_SPACE_AUDIT`
--
ALTER TABLE `HR_SPACE_AUDIT`
  ADD PRIMARY KEY (`SPACE_AUDIT_ID`),
  ADD KEY `FK_SPACE_ID` (`SPACE_ID`),
  ADD KEY `fk_SpaceAuditActionId` (`SPACE_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_TRAINING`
--
ALTER TABLE `HR_TRAINING`
  ADD PRIMARY KEY (`TRAINING_ID`);

--
-- Indexes for table `HR_TRAINING_AUDIT`
--
ALTER TABLE `HR_TRAINING_AUDIT`
  ADD PRIMARY KEY (`TRAINING_AUDIT_ID`),
  ADD KEY `FK_TRAINING_ID` (`TRAINING_ID`),
  ADD KEY `fk_TrainingAuditActionId` (`TRAINING_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_USER`
--
ALTER TABLE `HR_USER`
  ADD PRIMARY KEY (`USER_ID`),
  ADD UNIQUE KEY `AF_USER_ID_UNQ` (`AF_USER_ID`),
  ADD UNIQUE KEY `SSN_UNQ` (`USER_SSN`),
  ADD KEY `FK_USER_STATUS_ID` (`USER_STATUS_ID`),
  ADD KEY `FK_USER_SPRV_ID` (`USER_SPRV_ID`),
  ADD KEY `FK_USER_TYPE_ID` (`USER_TYPE_ID`),
  ADD KEY `FK_WORKFLOW_ID` (`ONBOARDING_WORKFLOW_ID`);

--
-- Indexes for table `HR_USER_AUDIT`
--
ALTER TABLE `HR_USER_AUDIT`
  ADD PRIMARY KEY (`USER_AUDIT_ID`),
  ADD KEY `fk_HRUserAuditAction` (`USER_AUDIT_ACTION_ID`);

--
-- Indexes for table `HR_WORKFLOW`
--
ALTER TABLE `HR_WORKFLOW`
  ADD PRIMARY KEY (`WORKFLOW_ID`),
  ADD KEY `FK_WF_WF_STATUS_ID` (`WORKFLOW_STATUS_ID`),
  ADD KEY `FK_WF_WF_TYPE_ID` (`WORKFLOW_TYPE_ID`),
  ADD KEY `FK_CURRENT_TASK_TYPE_ID` (`CURRENT_TASK_TYPE_ID`);

--
-- Indexes for table `HR_WORKFLOW_COMMENT`
--
ALTER TABLE `HR_WORKFLOW_COMMENT`
  ADD PRIMARY KEY (`COMMENT_ID`),
  ADD KEY `FK_COMMENT_WORKFLOW_ID` (`WORKFLOW_ID`) USING BTREE;

--
-- Indexes for table `HR_WORKFLOW_DOCUMENT`
--
ALTER TABLE `HR_WORKFLOW_DOCUMENT`
  ADD PRIMARY KEY (`DOC_ID`),
  ADD KEY `FK_DOC_WORKFLOW_ID` (`WORKFLOW_ID`) USING BTREE;
  
--
-- Indexes for table `HR_WORKFLOW_TASK`
--
ALTER TABLE `HR_WORKFLOW_TASK`
  ADD PRIMARY KEY (`TASK_ID`),
  ADD KEY `FK_TASK_WORKFLOW_ID` (`WORKFLOW_ID`),
  ADD KEY `FK_TASK_TYPE_ID` (`TASK_TYPE_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `HR_BKGD_INV`
--
ALTER TABLE `HR_BKGD_INV`
  MODIFY `BKGDINV_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
--
-- AUTO_INCREMENT for table `HR_BUILDING`
--
ALTER TABLE `HR_BUILDING`
  MODIFY `BUILDING_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;
--
-- AUTO_INCREMENT for table `HR_BUILDING_AUDIT`
--
ALTER TABLE `HR_BUILDING_AUDIT`
  MODIFY `BUILDING_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;
--
-- AUTO_INCREMENT for table `HR_CAMPUS`
--
ALTER TABLE `HR_CAMPUS`
  MODIFY `CAMPUS_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;
--
-- AUTO_INCREMENT for table `HR_CAMPUS_AUDIT`
--
ALTER TABLE `HR_CAMPUS_AUDIT`
  MODIFY `CAMPUS_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
--
-- AUTO_INCREMENT for table `HR_FLOOR`
--
ALTER TABLE `HR_FLOOR`
  MODIFY `FLOOR_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=63;
--
-- AUTO_INCREMENT for table `HR_FLOOR_AUDIT`
--
ALTER TABLE `HR_FLOOR_AUDIT`
  MODIFY `FLOOR_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=115;
--
-- AUTO_INCREMENT for table `HR_IT_EQUIPMENT`
--
ALTER TABLE `HR_IT_EQUIPMENT`
  MODIFY `IT_EQUIPMENT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=973245;
--
-- AUTO_INCREMENT for table `HR_IT_EQUIPMENT_AUDIT`
--
ALTER TABLE `HR_IT_EQUIPMENT_AUDIT`
  MODIFY `IT_EQUIPMENT_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=202;
--
-- AUTO_INCREMENT for table `HR_L_USER_TRAINING`
--
ALTER TABLE `HR_L_USER_TRAINING`
  MODIFY `USER_TRAINING_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
--
-- AUTO_INCREMENT for table `HR_POSTN`
--
ALTER TABLE `HR_POSTN`
  MODIFY `POSTN_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;
--
-- AUTO_INCREMENT for table `HR_POSTN_AUDIT`
--
ALTER TABLE `HR_POSTN_AUDIT`
  MODIFY `POSTN_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=183;
--
-- AUTO_INCREMENT for table `HR_POSTN_DESC`
--
ALTER TABLE `HR_POSTN_DESC`
  MODIFY `POSTN_DESC_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;
--
-- AUTO_INCREMENT for table `HR_POSTN_DESC_AUDIT`
--
ALTER TABLE `HR_POSTN_DESC_AUDIT`
  MODIFY `POSTN_DESC_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;
--
-- AUTO_INCREMENT for table `HR_RESERVATION`
--
ALTER TABLE `HR_RESERVATION`
  MODIFY `RESERVATION_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=237;
--
-- AUTO_INCREMENT for table `HR_RESERVATION_AUDIT`
--
ALTER TABLE `HR_RESERVATION_AUDIT`
  MODIFY `RESERVATION_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=356;
--
-- AUTO_INCREMENT for table `HR_SPACE`
--
ALTER TABLE `HR_SPACE`
  MODIFY `SPACE_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;
--
-- AUTO_INCREMENT for table `HR_SPACE_AUDIT`
--
ALTER TABLE `HR_SPACE_AUDIT`
  MODIFY `SPACE_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=103;
--
-- AUTO_INCREMENT for table `HR_TRAINING`
--
ALTER TABLE `HR_TRAINING`
  MODIFY `TRAINING_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `HR_TRAINING_AUDIT`
--
ALTER TABLE `HR_TRAINING_AUDIT`
  MODIFY `TRAINING_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `HR_USER`
--
ALTER TABLE `HR_USER`
  MODIFY `USER_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=60;
--
-- AUTO_INCREMENT for table `HR_USER_AUDIT`
--
ALTER TABLE `HR_USER_AUDIT`
  MODIFY `USER_AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `HR_WORKFLOW`
--
ALTER TABLE `HR_WORKFLOW`
  MODIFY `WORKFLOW_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=943;
--
-- AUTO_INCREMENT for table `HR_WORKFLOW_COMMENT`
--
ALTER TABLE `HR_WORKFLOW_COMMENT`
  MODIFY `COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;
--
-- AUTO_INCREMENT for table `HR_WORKFLOW_DOCUMENT`
--
ALTER TABLE `HR_WORKFLOW_DOCUMENT`
  MODIFY `DOC_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
--
-- AUTO_INCREMENT for table `HR_WORKFLOW_TASK`
--
ALTER TABLE `HR_WORKFLOW_TASK`
  MODIFY `TASK_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
--
-- Constraints for dumped tables
--


--
-- Constraints for table `HR_BKGD_INV`
--
ALTER TABLE `HR_BKGD_INV`
  ADD CONSTRAINT `FK_BKGD_INV_ADJTN_ID` FOREIGN KEY (`BKGDINV_ADJTN_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_BKGD_INV_STATUS_ID` FOREIGN KEY (`BKGDINV_STATUS_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_BKGD_INV_TTL_SEV_ID` FOREIGN KEY (`BKGDINV_TTL_SEV_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_BKGD_INV_TYPE_ID` FOREIGN KEY (`BKGDINV_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_BKGD_INV_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `HR_USER` (`USER_ID`);

--
-- Constraints for table `HR_BKGD_INV_ISSUE`
--
ALTER TABLE `HR_BKGD_INV_ISSUE`
  ADD CONSTRAINT `FK_BKGD_INV_ID` FOREIGN KEY (`BKGDINV_ID`) REFERENCES `HR_BKGD_INV` (`BKGDINV_ID`),
  ADD CONSTRAINT `FK_BKGD_INV_ISSUE_ID` FOREIGN KEY (`BKGDINV_ISSUE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_BUILDING`
--
ALTER TABLE `HR_BUILDING`
  ADD CONSTRAINT `CAMPUS_ID_FK` FOREIGN KEY (`CAMPUS_ID`) REFERENCES `HR_CAMPUS` (`CAMPUS_ID`);

--
-- Constraints for table `HR_BUILDING_AUDIT`
--
ALTER TABLE `HR_BUILDING_AUDIT`
  ADD CONSTRAINT `FK_BUILDING_AUDIT_ACTION_ID` FOREIGN KEY (`BUILDING_AUDIT_ACTION_ID`) REFERENCES `HR_R_BUILDING_AUDIT_ACTION` (`BUILDING_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_BUILDING_ID` FOREIGN KEY (`BUILDING_ID`) REFERENCES `HR_BUILDING` (`BUILDING_ID`);

--
-- Constraints for table `HR_CAMPUS_AUDIT`
--
ALTER TABLE `HR_CAMPUS_AUDIT`
  ADD CONSTRAINT `FK_CAMPUS_AUDIT_ACTION_ID` FOREIGN KEY (`CAMPUS_AUDIT_ACTION_ID`) REFERENCES `HR_R_CAMPUS_AUDIT_ACTION` (`CAMPUS_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_CAMPUS_ID` FOREIGN KEY (`CAMPUS_ID`) REFERENCES `HR_CAMPUS` (`CAMPUS_ID`);

--
-- Constraints for table `HR_FLOOR`
--
ALTER TABLE `HR_FLOOR`
  ADD CONSTRAINT `FLOOR_BUILDING_ID_FK` FOREIGN KEY (`BUILDING_ID`) REFERENCES `HR_BUILDING` (`BUILDING_ID`);

--
-- Constraints for table `HR_FLOOR_AUDIT`
--
ALTER TABLE `HR_FLOOR_AUDIT`
  ADD CONSTRAINT `FK_FLOOR_AUDIT_ACTION_ID` FOREIGN KEY (`FLOOR_AUDIT_ACTION_ID`) REFERENCES `HR_R_FLOOR_AUDIT_ACTION` (`FLOOR_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_FLOOR_ID` FOREIGN KEY (`FLOOR_ID`) REFERENCES `HR_FLOOR` (`FLOOR_ID`);

--
-- Constraints for table `HR_IT_EQUIPMENT`
--
ALTER TABLE `HR_IT_EQUIPMENT`
  ADD CONSTRAINT `FK_IT_EQUIP_EQUIP_TYPE` FOREIGN KEY (`IT_EQUIPMENT_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_IT_EQUIP_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `HR_USER` (`USER_ID`);

--
-- Constraints for table `HR_IT_EQUIPMENT_AUDIT`
--
ALTER TABLE `HR_IT_EQUIPMENT_AUDIT`
  ADD CONSTRAINT `FK_IT_EQUIPMENT_ID` FOREIGN KEY (`IT_EQUIPMENT_ID`) REFERENCES `HR_IT_EQUIPMENT` (`IT_EQUIPMENT_ID`),
  ADD CONSTRAINT `FK_IT_EQUIP_AUDIT_ACTION_ID` FOREIGN KEY (`IT_EQUIPMENT_AUDIT_ACTION_ID`) REFERENCES `HR_R_IT_EQUIPMENT_AUDIT_ACTION` (`IT_EQUIPMENT_AUDIT_ACTION_ID`);

--
-- Constraints for table `HR_L_USER_TRAINING`
--
ALTER TABLE `HR_L_USER_TRAINING`
  ADD CONSTRAINT `TRAINING_ID_FK` FOREIGN KEY (`TRAINING_ID`) REFERENCES `HR_TRAINING` (`TRAINING_ID`),
  ADD CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `HR_USER` (`USER_ID`);

--
-- Constraints for table `HR_POSTN`
--
ALTER TABLE `HR_POSTN`
  ADD CONSTRAINT `FK_STATUS_ID` FOREIGN KEY (`STATUS_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `fk_postn_user_id` FOREIGN KEY (`USER_ID`) REFERENCES `HR_USER` (`USER_ID`);

--
-- Constraints for table `HR_POSTN_AUDIT`
--
ALTER TABLE `HR_POSTN_AUDIT`
  ADD CONSTRAINT `FK_HR_POSTN_AUDIT_WORKFLOW_ID` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`),
  ADD CONSTRAINT `FK_HR_POSTN_ID_AUDIT` FOREIGN KEY (`POSTN_ID`) REFERENCES `HR_POSTN` (`POSTN_ID`),
  ADD CONSTRAINT `fk_PostnAuditActionId` FOREIGN KEY (`POSTN_AUDIT_ACTION_ID`) REFERENCES `HR_R_POSTN_AUDIT_ACTION` (`POSTN_AUDIT_ACTION_ID`);

--
-- Constraints for table `HR_POSTN_DESC`
--
ALTER TABLE `HR_POSTN_DESC`
  ADD CONSTRAINT `FK_AGENCY_ID` FOREIGN KEY (`AGENCY_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_DEPT_ID` FOREIGN KEY (`DEPT_ID`) REFERENCES `HR_R_DEPT` (`DEPT_ID`),
  ADD CONSTRAINT `FK_ELIGIBILITY_ID` FOREIGN KEY (`ELIGIBILITY_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `fk_postn_salary_freq` FOREIGN KEY (`SALARY_FREQUENCY_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `fk_postn_security_clearance` FOREIGN KEY (`SECURITY_CLEARANCE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_POSTN_DESC_AUDIT`
--
ALTER TABLE `HR_POSTN_DESC_AUDIT`
  ADD CONSTRAINT `FK_HR_POSTN_DESC_AUDIT_WORKFLOW_ID` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`),
  ADD CONSTRAINT `FK_HR_POSTN_DESC_ID_AUDIT` FOREIGN KEY (`POSTN_DESC_ID`) REFERENCES `HR_POSTN_DESC` (`POSTN_DESC_ID`),
  ADD CONSTRAINT `fk_PostnDescAuditActionId` FOREIGN KEY (`POSTN_DESC_AUDIT_ACTION_ID`) REFERENCES `HR_R_POSTN_DESC_AUDIT_ACTION` (`POSTN_DESC_AUDIT_ACTION_ID`);

--
-- Constraints for table `HR_RESERVATION`
--
ALTER TABLE `HR_RESERVATION`
  ADD CONSTRAINT `ORIG_RES_ID` FOREIGN KEY (`ORIG_RESERVATION_ID`) REFERENCES `HR_RESERVATION` (`RESERVATION_ID`),
  ADD CONSTRAINT `RESERVATION_USER_ID_FK` FOREIGN KEY (`RESERVATION_USER_ID`) REFERENCES `HR_USER` (`USER_ID`),
  ADD CONSTRAINT `SPACE_ID_FK` FOREIGN KEY (`SPACE_ID`) REFERENCES `HR_SPACE` (`SPACE_ID`);

--
-- Constraints for table `HR_RESERVATION_AUDIT`
--
ALTER TABLE `HR_RESERVATION_AUDIT`
  ADD CONSTRAINT `FK_RESERVATION_AUDIT_ACTION_ID` FOREIGN KEY (`RESERVATION_AUDIT_ACTION_ID`) REFERENCES `HR_R_RESERVATION_AUDIT_ACTION` (`RESERVATION_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_RESERVATION_ID` FOREIGN KEY (`RESERVATION_ID`) REFERENCES `HR_RESERVATION` (`RESERVATION_ID`);

--
-- Constraints for table `HR_R_WORKFLOW_TASK_TYPE`
--
ALTER TABLE `HR_R_WORKFLOW_TASK_TYPE`
  ADD CONSTRAINT `FK_WFTT_WORKFLOW_TYPE_ID` FOREIGN KEY (`WORKFLOW_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_WF_TYPE_ID` FOREIGN KEY (`WORKFLOW_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_SPACE`
--
ALTER TABLE `HR_SPACE`
  ADD CONSTRAINT `FK_SPACE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `HR_USER` (`USER_ID`),
  ADD CONSTRAINT `SPACE_FLOOR_ID` FOREIGN KEY (`FLOOR_ID`) REFERENCES `HR_FLOOR` (`FLOOR_ID`),
  ADD CONSTRAINT `SPACE_TYPE_ID_FK` FOREIGN KEY (`SPACE_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_SPACE_AUDIT`
--
ALTER TABLE `HR_SPACE_AUDIT`
  ADD CONSTRAINT `FK_SPACE_AUDIT_ACTION_ID` FOREIGN KEY (`SPACE_AUDIT_ACTION_ID`) REFERENCES `HR_R_SPACE_AUDIT_ACTION` (`SPACE_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_SPACE_ID` FOREIGN KEY (`SPACE_ID`) REFERENCES `HR_SPACE` (`SPACE_ID`);

--
-- Constraints for table `HR_TRAINING_AUDIT`
--
ALTER TABLE `HR_TRAINING_AUDIT`
  ADD CONSTRAINT `FK_TRAINING_AUDIT_ACTION_ID` FOREIGN KEY (`TRAINING_AUDIT_ACTION_ID`) REFERENCES `HR_R_TRAINING_AUDIT_ACTION` (`TRAINING_AUDIT_ACTION_ID`),
  ADD CONSTRAINT `FK_TRAINING_ID` FOREIGN KEY (`TRAINING_ID`) REFERENCES `HR_TRAINING` (`TRAINING_ID`);

--
-- Constraints for table `HR_USER`
--
ALTER TABLE `HR_USER`
  ADD CONSTRAINT `FK_AF_USER_ID` FOREIGN KEY (`AF_USER_ID`) REFERENCES `AF_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_ONBOARDING_WORKFLOW_ID` FOREIGN KEY (`ONBOARDING_WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`),
  ADD CONSTRAINT `FK_USER_SPRV_ID` FOREIGN KEY (`USER_SPRV_ID`) REFERENCES `HR_USER` (`USER_ID`),
  ADD CONSTRAINT `FK_USER_STATUS_ID` FOREIGN KEY (`USER_STATUS_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_USER_TYPE_ID` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_USER_AUDIT`
--
ALTER TABLE `HR_USER_AUDIT`
  ADD CONSTRAINT `fk_HRUserAuditAction` FOREIGN KEY (`USER_AUDIT_ACTION_ID`) REFERENCES `HR_R_USER_AUDIT_ACTION` (`USER_AUDIT_ACTION_ID`);

--
-- Constraints for table `HR_WORKFLOW`
--
ALTER TABLE `HR_WORKFLOW`
  ADD CONSTRAINT `FK_CURRENT_TASK_TYPE_ID` FOREIGN KEY (`CURRENT_TASK_TYPE_ID`) REFERENCES `HR_R_WORKFLOW_TASK_TYPE` (`TASK_TYPE_ID`),
  ADD CONSTRAINT `FK_WF_STATUS_ID` FOREIGN KEY (`WORKFLOW_STATUS_ID`) REFERENCES `HR_R_DATA` (`ID`),
  ADD CONSTRAINT `FK_WF_WF_TYPE_ID` FOREIGN KEY (`WORKFLOW_TYPE_ID`) REFERENCES `HR_R_DATA` (`ID`);

--
-- Constraints for table `HR_WORKFLOW_COMMENT`
--
ALTER TABLE `HR_WORKFLOW_COMMENT`
  ADD CONSTRAINT `FK_COMMENT_WORKFLOW_ID` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`);

--
-- Constraints for table `HR_WORKFLOW_DOCUMENT`
--
ALTER TABLE `HR_WORKFLOW_DOCUMENT`
  ADD CONSTRAINT `FK_DOC_WORKFLOW_ID` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`);

--
-- Constraints for table `HR_WORKFLOW_TASK`
--
ALTER TABLE `HR_WORKFLOW_TASK`
  ADD CONSTRAINT `FK_TASK_WORKFLOW_ID` FOREIGN KEY (`WORKFLOW_ID`) REFERENCES `HR_WORKFLOW` (`WORKFLOW_ID`);