/* *** Help Application - Version 1.0.0 Back-out script *** */

/* Drop Sequences */
DROP SEQUENCE AF_BLLTN_MSG_seq;
DROP SEQUENCE AF_USER_seq;
DROP SEQUENCE HELP_R_RSC_TYPE_seq;
DROP SEQUENCE HELP_R_RSC_CAT_seq;
DROP SEQUENCE HELP_R_RSC_SUBCAT_seq;
DROP SEQUENCE HELP_R_RSC_STS_seq;
DROP SEQUENCE HELP_R_RSC_TAG_seq;
DROP SEQUENCE HELP_RSC_seq;
DROP SEQUENCE HELP_RSC_CMMNT_seq;
DROP SEQUENCE HELP_RSC_FILE_seq;
DROP SEQUENCE HELP_RSC_LNK_seq;
DROP SEQUENCE HELP_RSC_RATING_seq;

/* Drop Triggers */
DROP TRIGGER AF_BLLTN_MSG_seq_tr;
DROP TRIGGER AF_USER_seq_tr;
DROP TRIGGER HELP_R_RSC_TYPE_seq_tr;
DROP TRIGGER HELP_R_RSC_CAT_seq_tr;
DROP TRIGGER HELP_R_RSC_SUBCAT_seq_tr;
DROP TRIGGER HELP_R_RSC_STS_seq_tr;
DROP TRIGGER HELP_R_RSC_TAG_seq_tr;
DROP TRIGGER HELP_RSC_seq_tr;
DROP TRIGGER HELP_RSC_CMMNT_seq_tr;
DROP TRIGGER HELP_RSC_FILE_seq_tr;
DROP TRIGGER HELP_RSC_LNK_seq_tr;
DROP TRIGGER HELP_RSC_RATING_seq_tr;

/* Drop Views */
DROP VIEW HELP_V_RESOURCE;

/* Drop Tables */
DROP TABLE AF_BLLTN_MSG CASCADE CONSTRAINTS;
DROP TABLE AF_USER CASCADE CONSTRAINTS;

DROP TABLE HELP_R_RSC_TYPE CASCADE CONSTRAINTS;
DROP TABLE HELP_R_RSC_SUBCAT CASCADE CONSTRAINTS;
DROP TABLE HELP_R_RSC_CAT CASCADE CONSTRAINTS;
DROP TABLE HELP_R_RSC_STS CASCADE CONSTRAINTS;
DROP TABLE HELP_R_RSC_TAG CASCADE CONSTRAINTS;
DROP TABLE HELP_RSC_CMMNT CASCADE CONSTRAINTS;
DROP TABLE HELP_RSC_FILE CASCADE CONSTRAINTS;
DROP TABLE HELP_RSC_LNK CASCADE CONSTRAINTS;
DROP TABLE HELP_RSC_RATING CASCADE CONSTRAINTS;
DROP TABLE HELP_L_RSC_TAG CASCADE CONSTRAINTS;
DROP TABLE HELP_RSC CASCADE CONSTRAINTS;